- src/breeding-insight/dao/ProgramUserDAO.ts
- src/breeding-insight/model/Program.ts
- src/breeding-insight/model/ProgramUser.ts
- src/breeding-insight/model/User.ts
- src/breeding-insight/service/ProgramUserService.ts
- src/breeding-insight/service/UserService.ts
- src/components/admin/AdminUsersTable.vue
- src/components/program/ProgramUsersTable.vue
- src/components/tables/BaseTable.vue
- src/components/tables/BaseTableRow.vue
Implements changes for the system user management design card, https://cornell.app.box.com/file/674491535345. 
Is paired with a bi-api card, PRO-53, and needs a version of bi-api running that branch to work properly. 
Included a way to hide columns on mobile devices in the data table. This feature was related because the admin users table takes up more space with the programs now. 
- Make sure a program is displayed when a user is added to a program. 
- Matches the design (besides items planned to be implemented in future cards)
- We can't assign a user to >1 program in our UI yet. You can use the queries in src/test/resources/sql/UserControllerIntegrationTest.sql to assign multiple programs to a user. Do this through DBeaver.
> [PRO-53] show programs for users

- src/breeding-insight/service/UserService.ts
Adds an error to the admin users page when a 403 response is returned on deactivate. 
Is pairs with ISSUE-5 PR of bi-api.
> [ISSUE-5] add delete user not allowed message

- src/components/forms/BaseFieldWrapper.vue
- src/components/forms/BasicInputField.vue
- src/components/forms/BasicSelectField.vue
- src/components/layouts/BaseSideBarLayout.vue
- src/components/layouts/UserSideBarLayout.vue
- src/components/tables/BaseTable.vue
- src/components/tables/PaginationControls.vue
Fixed the issues from the trello card. There were also issues in the new items form and edit items form that were fixed. I checked the trait import to see if there were any errors there, it was all good. 
Can be run with develop of bi-api.
> [ISSUE-6] fix wave errors

- src/components/program/ProgramUsersTable.vue
- tests/unit/components/program/ProgramUsersTable.spec.ts
- Bug fix - getting invalid fields notification even though a valid role is selected in the program management users table edit form
- Add a unit test to cover this scenario
> [PRO-80],[BI-61] - Fix Program Management Users role validation error

- package.json
Changes npm audit check to allow any dev vulnerabilities and no prod vulnerabilities
> [INF-206],[BI-63] change allowable npm audit levels

- .github/pr-labeler.yml
- .github/release-drafter.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/release-drafter.yml
Adding github actions for release drafter that were reviewed in the test-project.
> INF-202 - Development release notes and release drafter investigation

- package-lock.json
- package.json
- src/breeding-insight/model/view_models/TableRow.ts
- src/breeding-insight/service/ProgramLocationService.ts
- src/breeding-insight/service/ProgramUserService.ts
- src/breeding-insight/service/TraitUploadService.ts
- src/breeding-insight/service/UserService.ts
- src/components/layouts/UserSideBarLayout.vue
- src/components/program/ProgramLocationsTable.vue
- src/components/program/ProgramUsersTable.vue
- src/components/tables/BaseTable.vue
- src/components/tables/EmtpyTableMessage.vue
- src/components/tables/ExpandableRowTable.vue
- src/components/tables/ExpandableTableRow.vue
- src/components/tables/SidePanelTable.vue
- src/config/AppAbility.ts
- src/config/ability.ts
- src/main.ts
- src/router/guards.ts
- src/router/index.ts
- src/shims-ability.d.ts
- tests/unit/components/tables/BaseTable.spec.ts
- tests/unit/index.ts
- tsconfig.json
Introduces roles to the front end to hide/show different components. I followed rules set out on the card as well as defined rules from traits, which was not included in the cards. 
This will run separate from the bi-api branch of this. I still need to do some clean up on bi-api, but this branch shouldn't change during that clean up. 
I also modified the `ExpandableRowTable` element to have separate rules for archive and edit. They were a package deal before.
> [BI-601] - Implement role permissions on front end

- src/breeding-insight/model/import/ImportMapping.ts
- Bug fix for clearing mapping state being sent to api when switched
> BI-969 - Blueberry Penetrometer Import

- src/components/import/FieldMappingRow.vue
- src/components/import/RelationMappingRow.vue
- Added required/optional indicators for relation mapping fields, cleaned up text alignment
- Error messages seem to be working on latest code so would like to deploy to qa test and see
> [BI-965] QA Bug fixes

- src/views/trait/TraitsImport.vue
There is a new trait import template required for changes on the backend:
- "Trait name" is changed to "Ontology term name";
- "Trait level" is changed to "Trait entitiy";
- "Trait attribute" is added.
>  [BI-982] - Ontology BrAPI Mapping for Trait

- src/components/layouts/menus/UserStatusMenu.vue
Add ids for taf testing of user status menu.
> Add ids for taf testing

- src/router/index.ts
- src/views/PageNotFound.vue
- Added PageNotFound.vue component to direct to if a user is logged in and the page is not found. 
- If user is not logged in, the router will keep to pre-existing logic of redirecting to the home page if a not authorized error is not returned.
> BI-369 Handle state for "Page does not exist"

- package.json
- src/breeding-insight/dao/ProgramDAO.ts
- src/breeding-insight/model/Program.ts
- src/breeding-insight/service/ProgramService.ts
- src/components/admin/AdminProgramsTable.vue
- src/components/forms/BaseFieldWrapper.vue
- src/components/forms/BasicInputField.vue
- Added field on admin program create for user to input a string for the program key
- This field is not present for updating programs.
- Added handling for checking if key is already in use
- Added front-end validations for key
Linked to PR [bi-api/BI-1201](https://github.com/Breeding-Insight/bi-api/pull/114)
> [BI-1201] Add 'Program Key' field to Program Create

- src/views/import/ImportGermplasm.vue
- Create default germplasm import mapping based on the template
- Associate default germplasm import mapping with germplasm import functionality
Linked to PR [bi-api/BI-1176](https://github.com/Breeding-Insight/bi-api/pull/116)
> [BI-1176] Create Germplasm Template Mapping

- src/breeding-insight/model/Trait.ts
- tests/unit/models/trait.spec.ts
for https://breedinginsight.atlassian.net/browse/BI-1254
The back-end should be release/0.4
> [BI-1254] git trait tags and synonyms default values

- src/views/import/ImportGermplasm.vue
- src/views/import/ImportTemplate.vue
This includes some fixes to the front end of the germplasm import that I noticed as I was working on 1055 for the backend. 
It is mainly fixes to better error reporting and displaying of the data.
> [BI-1055] Save germplasm

- src/breeding-insight/dao/ImportDAO.ts
- src/breeding-insight/model/GermplasmList.ts
- src/breeding-insight/model/import/ImportField.ts
- src/breeding-insight/service/ImportService.ts
- src/views/import/BrAPIImporter.vue
- src/views/import/ImportGermplasm.vue
- src/views/import/ImportTemplate.vue
- Adds user inputs to the germplasm import during preview
- Adds user inputs to the brapi importer during preview
- Includes display of error banner if the list name is not provided. 
- bi-api BI-1085
- See bi-api BI-1085 for testing details.
> [BI-1085] - Germplasm import user input

- src/views/trait/TraitsImport.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1256
Simple navigation fix
bi-api: develop 
Use this file to get a successful import and check that it navigates you to the correct page after confirming. 
[BI_1256_good_traits.xls](https://github.com/Breeding-Insight/bi-web/files/8017767/BI_1256_good_traits.xls)
> [BI-1256] traits import: fix post confirm navigation

- src/views/import/ImportOntology.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1373
Simple fix to pass through all listeners for ontology import component. 
bi-api:develop
Run the tests from the card. Here are two files you can use:
[BI_1373_bad_traits.xls](https://github.com/Breeding-Insight/bi-web/files/8089481/BI_1373_bad_traits.xls)
[BI_1373_good_traits.xls](https://github.com/Breeding-Insight/bi-web/files/8089482/BI_1373_good_traits.xls)
> [BI-1373] ontology import: fix banners

- src/router/index.ts
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1106
A simple route fix for the observations page. 
Follow scenario from JIRA card.
> [BI-1106] observations list: fix route

- src/components/admin/AdminProgramsTable.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1336
All of the infrastructure was there, the table was just not updated to included species sorting. 
Creating programs with various species. Check that they sort correctly.
> [BI-1336] Programs table: fix species sort

- src/components/layouts/UserSideBarLayout.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1416
Simple nav fix.
biapi: develop
Launch it up, test the link.
> [BI-1416] import ontology: fix nav

- src/breeding-insight/dao/GermplasmDAO.ts
- src/breeding-insight/service/GermplasmService.ts
- src/components/germplasm/GermplasmListsTable.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1399
Added backend pagination to the germplasm lists table. 
biapi: BI-1399
sgn: BI-1399
Import the following file into a breedbase program 11+ times and then test the pagination.
> [BI-1399] Fix germplasm lists pagination

- src/views/import/ImportGermplasm.vue
**Story:** https://breedinginsight.atlassian.net/wiki/spaces/BI/pages/1554907145/Breeding+Methods+Validations
Updated link to new germplasm template. 
bi-api: BI-1397
See bi-api PR for testing details.
> [BI-1397] germplasm import: update template

- src/breeding-insight/dao/GermplasmDAO.ts
- src/breeding-insight/model/Sort.ts
- src/breeding-insight/model/User.ts
- src/breeding-insight/model/errors/ValidationError.ts
- src/breeding-insight/model/import/germplasm/ExternalUID.ts
- src/breeding-insight/service/GermplasmService.ts
- src/breeding-insight/service/ImportService.ts
- src/breeding-insight/service/UserService.ts
- src/components/admin/AdminProgramsTable.vue
- src/components/admin/AdminUsersTable.vue
- src/components/file-import/FileSelectMessageBox.vue
- src/components/file-import/MultipleErrors.vue
- src/components/germplasm/GermplasmListsTable.vue
- src/components/layouts/UserSideBarLayout.vue
- src/components/ontology/OntologyTable.vue
- src/components/ontology/OntologyTable.vue.js
- src/components/program/ProgramUsersTable.vue
- src/components/trait/TraitDetailPanel.vue
- src/components/trait/TraitsImportTable.vue
- src/components/trait/forms/BaseTraitForm.vue
- src/components/trait/forms/CategoryTraitForm.vue
- src/router/index.ts
- src/store/sorting/getters.ts
- src/store/sorting/index.ts
- src/store/sorting/mutations.ts
- src/store/sorting/types.ts
- src/views/import/BrAPIImporter.vue
- src/views/import/ImportGermplasm.vue
- src/views/import/ImportOntology.vue
- src/views/program/ProgramSelection.vue
Merge branch to update develop with release bug fixes.
biapi: develop-release0.5-merge
> Update develop with release bug fixes

- src/components/ontology/OntologyTable.vue
- src/components/trait/TraitsImportTable.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1360
Fixes undefined method description in trait preview. 
Also fixes bad nav for `Import Batch File` on ontology page. 
biweb: release/0.5
1. Import a file with no method description
2. Make sure it doesn't show up in the preview table as `undefined`
3. Click on the "Import Batch File" button and make sure it takes you to the import ontology page.
> [BI-1360] Fix undefined method in trait preview

- src/components/ontology/OntologyTable.vue
- src/components/trait/TraitsImportTable.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1360
See https://github.com/Breeding-Insight/bi-web/pull/211 for details.
> [BI-1360] Fix undefined method in trait preview, develop

- src/components/program/SubscribeOntologyConfiguration.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1366
Text changes and notifications to match the tech specs. 
biapi: develop
See Shahana's comments on JIRA card and make sure all of those points were addressed.
> [BI-1366] subscribe ontology: text changes and better user notifications

- src/breeding-insight/model/view_models/BackendPaginationController.ts
- src/components/admin/AdminProgramsTable.vue
- src/components/admin/AdminUsersTable.vue
- src/components/germplasm/GermplasmListsTable.vue
- src/components/ontology/OntologyTable.vue
- src/components/program/ProgramLocationsTable.vue
- src/components/program/ProgramUsersTable.vue
- src/components/tables/PaginationControls.vue
- src/components/trait/TraitsImportTable.vue
- src/views/germplasm/GermplasmTable.vue
**Story:** [“Show All” for programs pagination doesn’t work if user is on the last page of pagination
](https://breedinginsight.atlassian.net/browse/BI-1401)
Logic for toggling showAll failed on pages beyond page 2 (and only really worked on page 2 due to sheer luck of math). This change passes the correct page and pageSize information to the backend when showAll is toggled, regardless of starting page.
In addition, logic was added to ensure that when a new entry was added when the showAll toggle was selected, the pageSize increases by 1 so it does not spill over onto a second page.
This affects the following tables:
- AdminProgramsTable.vue
- AdminUsersTable.vue
- OntologyTable.vue
- ProgramLocationsTable.vue
- ProgramUsersTable.vue
- TraitsImportTable.vue
GermplasmTable.vue and …
> [BI-1401] - Fixing showAll for pagination beyond page 2

- src/views/import/ImportGermplasm.vue
**Story:** 
[BI-1491 - New Breeding Method - Polyembryonic seed selection](https://breedinginsight.atlassian.net/browse/BI-1491)
[BI-1527 - New Breeding Method - Creation of triploids by applied pressure or temperature shock](https://breedinginsight.atlassian.net/browse/BI-1527)
[BI-1528 - New Breeding Method - Creation of tetraploids by applied pressure shock](https://breedinginsight.atlassian.net/browse/BI-1528)
Added 3 new breeding methods to germplasm import template
Created flyway migration to add the new breeding methods to breeding methods table
[bi-api: feature/BI-1491](https://github.com/Breeding-Insight/bi-api/pull/198)
Go to Import Germplasm and download Germplasm Import Template
'Clone formation (PES)', 'Induced triploidy', and 'Induced tetraploidy' should be in breeding …
> [BI-1491] [BI-1527] [BI-1528] Add more breeding methods

- src/views/import/ImportExperiment.vue
I misspelling of the word "Germplasm" in the _Import Summary_ section  of the _confirmation screen_ of the Experiment Import
bi_api branch feature/BI-1189
> Fixed type-o

- src/breeding-insight/model/Sort.ts
**Story:** [BI-1557](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1557)
The germplasm sort field enums in `Sort.ts` of bi-web was updated to match the fields in `GermplasmQuery.java` model in bi-api.
develop branch of bi-api
import germplasm with values for every column in the germplasm table. Click on each column to sort in ascending and descending order.
> [BI-1557] Sorting Failures in Germplasm Table

- src/components/layouts/UserSideBarLayout.vue
- src/router/index.ts
- src/views/import/ImportFile.vue
- src/views/program/ProgramManagement.vue
**Story:** [BI-1569](https://breedinginsight.atlassian.net/browse/BI-1569?atlOrigin=eyJpIjoiYjVkMTllZDg1YzYxNGFiN2EzYjFmNjhhZTM4YjExYmMiLCJwIjoiaiJ9)
- Moved Experiments & Observations menu item to match source of truth
- Renamed BrAPI Import to Data Mapping and updated url path on Import page
- Renamed Program users and Program locations titles
- Renamed system admin page titles
- BI-1651 will reorder Program Administration tabs once merged
- bi-api develop
- Verify that menu and tab item order and naming matches source of truth as specified in card linked document
[BI-1569]: https://breedinginsight.atlassian.net/browse/BI-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-1569 - Update within program left hand menu

- README.md
Fixed style guide URL path in README.md.
> [update-readme] - fixed style guide URL path in README.md

- src/breeding-insight/model/DatasetTableRow.ts
- src/breeding-insight/model/GeoCoordinates.ts
- src/breeding-insight/model/ObservationUnit.ts
- src/views/import/Dataset.vue
- src/views/import/ImportExperiment.vue
**Story:** [BI-2005](https://breedinginsight.atlassian.net/browse/BI-2005?atlOrigin=eyJpIjoiOGMyYjY3OTU1OTc0NGFiZmFjODIzOTM0ZjllM2QzYzgiLCJwIjoiaiJ9)
- created a new experiment template file and updated box link
- Added geocoordinate columns to experiment preview and view tables
- bi-api branch: feature/BI-2005
- Ensure that validations as specified in card work
[BI-2005]: https://breedinginsight.atlassian.net/browse/BI-2005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-2005 - Expand Exp Template

- src/views/import/Dataset.vue
[BI-2126](https://breedinginsight.atlassian.net/browse/BI-2126) Env year missing from dataset view
Now the Env Year is fetched on the back-end and passed to the front-end in the _additional_Info_ element of each Observation Unit.
bi-api: bug/BI-2126 branch
1. Vew any experiment.
* The correct Env Year should be displayed for each Observation Unit.
[BI-2126]: https://breedinginsight.atlassian.net/browse/BI-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BI-2126] Env year missing from dataset view

- src/views/experiments-and-observations/ExperimentDetails.vue
[BI-2154](https://breedinginsight.atlassian.net/browse/BI-2154) -  Adjust Read Only permissions
bi-api: **develop**
See Acceptance Criteria in [BI-2154](https://breedinginsight.atlassian.net/browse/BI-2154)
[BI-2154]: https://breedinginsight.atlassian.net/browse/BI-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BI-2154] Adjust Read Only permissions

- src/breeding-insight/utils/GermplasmUtils.ts
See https://github.com/Breeding-Insight/bi-web/pull/399 for details.
> BI-2304 - merge into release/1.0

- src/views/Home.vue
**Story:** [BI-2336](https://breedinginsight.atlassian.net/browse/BI-2336?atlOrigin=eyJpIjoiZDY2N2I3MGIyMTUxNDZlNjk5ODkzZjYyYTBkNzMzODEiLCJwIjoiaiJ9)
- Removed user panel entirely after discussing with Shawn
- None
- Verify that user panel is no longer shown on Home page
[BI-2336]: https://breedinginsight.atlassian.net/browse/BI-2336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BI-2336 - Remove or reposition text "Placeholder image" from DeltaBreed program homepage

- src/views/experiments-and-observations/ExperimentDetails.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-2425
Temporarily enabling this option for testing, it will be reverted for the v1.1 release.
> BI-2425 - Enable Sub-Entity Work in Progress on QA-Test
