src/breeding-insight/service/ProgramLocationService.ts, src/breeding-insight/service/ProgramService.ts, src/breeding-insight/service/ProgramUserService.ts
Removes workarounds for the `data` object not being included in the response if no results were in the data response. Goes with bi-api INF-138.
=> [INF-138] Remove workaround for data not existing in response

src/breeding-insight/service/ProgramUserService.ts, src/components/program/ProgramUsersTable.vue
Modifies the front end to be able to send add an existing user to the program. 
I modified the front end instead of the backend so that we could keep our desired behavior for the endpoints in the front end. When an acting user adds a user to a program, the front end checks if a system user with that email exists, and gets the id from that user if so. The front end then uses its existing methods to POST the user. When the response returns, we check if the id of the returned user matches the id of one of the existing users, and shows a notification indicating an existing user was added to the program. 
- Look in the system users table and copy one of the ids there. 
- Create a few programs
- Go into each of the programs and add a user with the copied email above
- When you save, make sure …
=> [INF-75] add ability to add existing user to program

src/breeding-insight/model/ProgramUser.ts, src/components/program/ProgramUsersTable.vue
Adds a manual entry of the orcid to the admin users and program users endpoints. 
- Most extra orcid logic is added to the services and daos for easy removal. There is some stuff in the view pages that will have to be removed as well. 
- In Program Users, if the orcid (or email) matches an existing (and active) user, that existing user will be added to the program. 
- In Admin Users, if you add a valid user with a duplicate user id, there will be an error message that the user was created, by the orcid was a duplicate. The user will be created, but the id will not be assigned. You can assign this later. 
- Same goes for updating a user in admin users. 
- In Program Users, if an orcid overlaps the orcid of an inactive user, it will not add the inactive user to the program, it will show a …
=> [PRO-78] manual entry of orcids

src/breeding-insight/service/PromiseHandler.ts, src/breeding-insight/service/UserService.ts, src/components/admin/AdminUsersTable.vue
There are two updates that are being made when you edit the user:
1. Update user info
2. Update user roles
From the card, when you try to edit your user in the admin users table, it shows an error, but updates the name successfully. It shows as an error because in #2 a user can't edit their own roles. I edited the error reporting to show a success for the update of the user, and a failure for the role update. If there is more than one error (both user info, and user roles calls fail), the user info error will be shown. We can show both once we implement the feature for multiple notifications of the same type.
=> [ISSUE-4] update multiple calls error handling to better report partial success

src/breeding-insight/service/ProgramUserService.ts, src/breeding-insight/service/UserService.ts, src/components/admin/AdminUsersTable.vue, src/components/forms/BasicInputField.vue, src/components/forms/BasicSelectField.vue, src/components/program/ProgramUsersTable.vue, tests/unit/components/program/ProgramUsersTable.spec.ts, tests/unit/test-utils/DaoUtils.ts
Based off bug/PRO-80, so review and approve that one first. 
This bug fix fixes a bug where you can update the orcid when creating a program user for a system user that already exists. Previously, if there was an email match, the orcid would be updated for the existing user. Bug fix makes it so the update orcid action is not made when there is an email match. 
Also adds a not documented bug where if the email and orcid you enter reference two different users, it would arbitrarily choose one. I made it so it throws an error if this condition is met.
=> [ISSUE-8],[BI-540] Fix orcid overwrite when adding new program user for existing system user

src/App.vue, src/breeding-insight/service/UserService.ts, src/components/admin/AdminUsersTable.vue, src/components/notifications/WarningNotification.vue, tests/unit/components/admin/AdminUsersTable.spec.ts, tests/unit/components/program/ProgramUsersTable.spec.ts
Fixes the issue of the new data form being left open when a user is successfully saved but their orcid is not updated properly. 
Additions:
- Added a duplicate orcid check before making POST check.
- Closed new data form if user POST is successful, but orcid PUT is not. 
- Added validation for orcid
- Changed addUser method to use async/await for clearer error handling and request flow. 
Note: 
Updating the users uses a similar request flow to what adding users used to be before updating to use async/await. I did not change update users because I did not want this card to get too out of scope. 
The pre-check for a duplicate orcid does not take into account deactivated users. Our API is not capable of returning inactive users yet. The backend will still catch duplicates for inactive users …
=> [BI-72] - Error adding new user with already existing orcid, form stays open

.env.development, src/App.vue, src/components/layouts/BaseSideBarLayout.vue, src/components/layouts/SimpleLayout.vue, src/components/notifications/SandboxCoordinatorNotification.vue, src/components/notifications/SandboxPublicNotification.vue, src/main.ts, src/router/index.ts, src/shims-tsx.d.ts, src/store/index.ts, src/store/mutation-types.ts, src/store/mutations.ts, src/store/types.ts, src/util/config.ts
- Added configuration variable for setting sandbox mode if desired
- Added sandbox notifications that appear on first visit if in a sandbox mode
- Added sandbox header item that appears if in a sandbox mode
- Feedback form goes to JIRA issue collectors (BI Feedback project)
- One issue collector for Public and one for Coordinator depending on sandbox mode
A cookie is used to track whether this is the user's first visit to the site. If it is and in a sandbox mode, then the sandbox notification will be displayed. The cookie currently is set to expire after 1 week but we can adjust the time frame to whatever.
- Verify that setting the VUE_APP_SANDBOX config in `.env.development` to public, coordinator, and removing works as expected
- Verify first visit notification works
- Can delete …
=> BI-57 - Set up sandbox sites

src/breeding-insight/dao/ProgramDAO.ts, src/breeding-insight/dao/ProgramLocationDAO.ts, src/breeding-insight/dao/ProgramUserDAO.ts, src/breeding-insight/dao/TraitDAO.ts, src/breeding-insight/dao/TraitUploadDAO.ts, src/breeding-insight/dao/UserDAO.ts
Change to DAOs to work with new backend pagination. The DAOs now do not send back any params so that all results are returned by default. 
Poked around and tested out each page table. Seems to work.
=> [BI-611] make daos work with pagination in backend

src/components/admin/AdminUsersTable.vue, tests/unit/components/admin/AdminUsersTable.spec.ts
Allows OrcID's to have `X` as the last character.
=> [BI-637] orcid last character X fix plus test

.env.development, src/breeding-insight/dao/UserDAO.ts, src/breeding-insight/service/UserService.ts, src/router/index.ts, src/views/Index.vue, src/views/NotAuthorized.vue
Fixes issue with the nonce token (a token in the openid handshake that identifies a request upon return to open id requestor) expiring during the login process. The token still expires, but a bad token validation is handled and the user is notified on the front page to try again. I increase the expiration time to 10 minutes (it was 5 minutes). 
I also included a way to log out of open id before beginning the login process. This should be able to handle any Open ID provider if they have a logout URI. The logout url isn't required, and the process skips over that part if the logout attempt fails, or if the url isn't provided in the config. 
https://github.com/Breeding-Insight/bi-api/pull/51
1. Try changing the cookie expiration to 1s and check that you get the right page (see below)
2. Try …
=> [BI-626] Handle login error and logout user before starting login process

.github/workflows/release-drafter.yml, .github/workflows/versioner-develop.yml, package-lock.json, package.json, src/App.vue, src/assets/scss/main.scss, src/breeding-insight/dao/ServerManagementDAO.ts, src/breeding-insight/model/ApiInfo.ts, src/components/layouts/BaseSideBarLayout.vue, src/components/layouts/Footer.vue, src/components/layouts/VersionInfo.vue
Display the current version of both bi-web and bi-api on the page, and provide a link to the GitHub release (or commit if running `develop`).  This can be useful for debugging purposes, as well as for identifying what features are deployed to a given server.  The implementation of updating and sharing version info of bi-api is in https://github.com/Breeding-Insight/bi-api/pull/54.  Here's a design of placement of the version info:
The version information for bi-web is stored in `package.json`.  The version name is stored in the `version` property, and a link to the release (or commit) is stored in a custom property named `versionInfo`.  These properties are automatically updated and committed to the repo via GitHub Actions.  
When merging to `master`, the action will use the output from …
=> [BI-379] Display web and API build version on UI

.github/workflows/versioner-develop.yml, package.json, src/components/trait/TraitImportTemplateMessageBox.vue
Update file template for trait upload
=> [BI-686] update file template

package-lock.json, package.json, src/assets/scss/main.scss, src/breeding-insight/dao/ProgramDAO.ts, src/breeding-insight/dao/TraitDAO.ts, src/breeding-insight/dao/TraitUploadDAO.ts, src/breeding-insight/model/BiResponse.ts, src/breeding-insight/model/Method.ts, src/breeding-insight/model/ObservationLevel.ts, src/breeding-insight/model/Scale.ts, src/breeding-insight/model/Trait.ts, src/breeding-insight/service/ProgramService.ts, src/breeding-insight/service/TraitService.ts, src/breeding-insight/service/TraitUploadService.ts, src/components/forms/BaseFieldWrapper.vue, src/components/forms/BasicSelectField.vue, src/components/forms/NewDataForm.vue, src/components/trait/TraitDetailPanel.vue, src/components/trait/TraitListsTable.vue, src/components/trait/TraitsImportTable.vue, src/components/trait/forms/BaseTraitForm.vue, src/views/TraitsImport.vue
Adds the ability to create a basic trait from the UI. 
Error display is not implemented yet, so you will get a generic error when trait creation fails. Open the developer console to see the errors printed out. You might need the console open before submitting for the errors to be printed. 
Some scale classes may fail because the specific scale additionals aren't in there yet. You will get errors like "Missing categories for scale class 'Categories'" or something along those lines. 
Some updates to the components. One to allow hiding of the label. One to allow the select field component to accept strings and objects.
=> [BI-85,BI-646] - Create new trait UI

src/components/trait/TraitDetailPanel.vue, src/components/trait/forms/BaseTraitForm.vue, src/components/trait/forms/DurationTraitForm.vue, src/components/trait/forms/NumericalTraitForm.vue, src/components/trait/forms/TextTraitForm.vue
Based off other PR, [BI-671] so will include extra file changes. 
[BI-671]: https://breedinginsight.atlassian.net/browse/BI-671
=> [BI-683, BI-678, BI-670] - Numerical, Text, Duration scale forms

src/components/trait/TraitImportTemplateMessageBox.vue, src/components/trait/forms/BaseTraitForm.vue, src/components/trait/forms/CategoryTraitForm.vue, src/components/trait/forms/DateTraitForm.vue, src/components/trait/forms/LabelValueRow.vue, src/components/trait/forms/ValueRow.vue
Added the calendar scale class and the computation method class. Also added a history to the scale classes and the method formula.
=> [BI-684, BI-682] - Calendar scale and Computation method class

src/assets/scss/main.scss, src/breeding-insight/model/errors/RowError.ts, src/breeding-insight/model/errors/TraitError.ts, src/breeding-insight/model/errors/TraitErrorHandler.ts, src/breeding-insight/model/errors/ValidationError.ts, src/components/file-import/FileSelectMessageBox.vue, src/components/forms/AutoCompleteField.vue, src/components/forms/BaseFieldWrapper.vue, src/components/forms/BasicInputField.vue, src/components/notifications/ErrorNotification.vue, src/components/trait/TraitListsTable.vue, src/components/trait/forms/BaseTraitForm.vue, src/components/trait/forms/CategoryTraitForm.vue, src/components/trait/forms/DurationTraitForm.vue, src/components/trait/forms/LabelValueRow.vue, src/components/trait/forms/NumericalTraitForm.vue, src/components/trait/forms/ValueRow.vue
PAIRED WITH TEMPLATE UPDATE. UPDATE LINK AFTER APPROVAL:
https://github.com/Breeding-Insight/requirements/pull/16
Also includes a fix to feather icons so that they line up with text properly. 
Maps the server errors to the UI inputs. Some custom parsing needed to be done for `units` because the field they go into is `scaleName`. It's not perfect, but it works for what we are doing. 
The design for the error icons changed slightly after speaking with Liz. I put them in the error text instead of in the input because it was easier for the same effect.
=> [BI-685] - Map backend trait validation errors to front end

.env.development, vue.config.js
bi-web was referencing an incorrect field in package.json.  The field needed to be `versionInfo` instead of `versionTag`
=> [BI-680] Fixing invalid versionInfo URL for bi-web

src/assets/scss/main.scss
Description: zebra-striping when editing Users page
Component/Version: rel-test v0.2
Browsers: Chrome, Edge, Opera, Firefox
Steps to Reproduce:
login as as an admin
navigate to Users - take note of the striping to denote different rows
choose a user whose current stripe is grey, select edit - note row stays grey
choose a user whose current stripe is white, select edit - note row turns purple
Expected result:
striping stayed in the same pattern   modified 1/8/20 per discussion w/Liz & Tim
the row being edited should be purple whether original stripe is grey or white
Actual Result:
striping goes off pattern
the row remains grey if the original row color is grey - added 1/8/20
the row turns purple if the original row color is white- added 1/21/20
=> [BI-701] match even/odd striped row backgrounds when selected for edit

src/breeding-insight/dao/TraitDAO.ts, src/components/trait/TraitDetailPanel.vue, src/components/trait/TraitListsTable.vue, src/components/trait/forms/BaseTraitForm.vue
Hook up the PUT traits on the front end to the backend. 
See other PRs:
https://github.com/Breeding-Insight/bi-api/pull/68
https://github.com/Breeding-Insight/sgn/pull/7
=> [BI-677] - Connect PUT traits to back end

src/components/program/ProgramUsersTable.vue
If the active user is being added to a program then the active user roles are updated as part of the success handler.
Description: Import Traits not available until refreshing page after adding self to program
Component/Version: v0.2
Steps to Reproduce
login as admin
add self to a program
select traits in left navigation bar
Expected result:
Import Traits visible as a selection 
Actual Result:
Import traits not visible until the page is refreshed
=> [BI-698] Import Traits not available until refreshing page after adding self to program

package.json, src/assets/scss/main.scss, src/breeding-insight/dao/TraitDAO.ts, src/breeding-insight/model/Trait.ts, src/breeding-insight/service/TraitService.ts, src/components/tables/SidePanel.vue, src/components/trait/TraitDetailPanel.vue, src/components/trait/TraitListsTable.vue
The Trait model was updated to include the "active" property and set it to true by default.
The Archiving features in the UI can be activated/deactivated by toggle the state of the archivable prop in TraitsListTable.
Archivable should be set to false until the "active" property is included in trait data from bi-api.
Given: The user has navigated to the "Trait Management" screen
And: the user has selected a trait to view
When: the user clicks "Archive" on the detail pane
Then: ensure that a confirmation dialog appears
Given: The user has clicked “Archive”
When: they confirm archiving the trait
Then: ensure that the trait detail pane is closed
And: ensure that the row shows an indicator that the trait is archived
And: ensure that a success notification is displayed at the top of the screen …
=> [BI-563] Archive Individual Trait

src/components/trait/forms/BaseTraitForm.vue
Fixed a bug in the setScaleClass method of BaseTraitForm.vue. Now the dataType of nominal and ordinal is explicitly set.
=> [BI-769] assign nominal and ordinal data types when setting new trait scale

src/components/trait/forms/BaseTraitForm.vue
The fixes used in this PR for the method of setting the scale class when using the new-trait form also satisfies
BI-796 ISSUE: Trait Create/Edit - Labels for Ordinal inconsistent 
BI-797 ISSUE: Trait Create/Edit - Labels for Ordinal not remembered when switching between scale classes
https://breedinginsight.atlassian.net/browse/BI-796
https://breedinginsight.atlassian.net/browse/BI-797
=> Fix/BI-794 ISSUE: New/Edit Trait - ordinal scale name for new traits persists in db after changing scale name to nominal

package-lock.json, package.json, src/breeding-insight/dao/TraitDAO.ts, src/breeding-insight/service/TraitService.ts, src/components/trait/TraitDetailPanel.vue, src/components/trait/TraitListsTable.vue
Possible future improvements (don't want to spend more time on this currently):
- caching editable status
- cancelling editable requests when table row is changed
=> BI-690 - Edit existing trait which has observation data

src/components/trait/TraitDetailPanel.vue, src/components/trait/TraitListsTable.vue, src/config/ability.ts
Added abilities of `create` and `update` of `Trait` to the `breeder` role, and then enforced them by hiding or showing create, edit, and archive buttons (breeder can see the buttons, member cannot).
=> [BI-846] - Hiding create/edit buttons for traits for member role

src/components/trait/forms/NumericalTraitForm.vue
On our UI we had the help text for scale valid value min/max as `Numbers only. Decimals ok.`. BrAPI doesn't not support decimals places in these fields, neither does our backend. The import template correctly states that only integers are supported. 
See bi-api change: 
https://github.com/Breeding-Insight/bi-api/pull/94
=> [BI-986] - Change scale valid value min/max text

package.json, src/components/file-import/FileSelectMessageBox.vue, src/components/file-import/FileSelector.vue, src/components/layouts/BaseSideBarLayout.vue, src/components/layouts/UserSideBarLayout.vue, src/components/trait/TraitImportTemplateMessageBox.vue, src/views/trait/TraitsImport.vue
Adding IDs to buttons to make TAF testing more robust (as opposed to using xpaths for selectors).
- Download the Trait Import Template
- Choose a file…
- Choose a different file…
- Import
- Yes, abort
- Log out
- Home
- Import File
- Program Management
- Traits
- BrAPI
- Users
- Programs
Convention: lowercase, separated by dashes, prefaced with component name, ie: “fileselector-choose-file”
Linked to https://github.com/Breeding-Insight/taf/pull/3 which modifies associated TAF tests
=> [BI-972] - Testing Automation Framework (TAF) Button ID selectors

src/components/file-import/FileSelectMessageBox.vue
The TAF tests checking for the display of uploaded filename are currently failing.
- Added an id to the div with the filename in FileSelectMessageBox.vue
Associated with PR [taf/1025](https://github.com/Breeding-Insight/taf/pull/6)
=> [BI-1025] - Id added for imported file name

src/components/notifications/ErrorNotification.vue, src/components/notifications/InfoNotification.vue, src/components/notifications/SuccessNotification.vue, src/components/notifications/WarningNotification.vue
To make TAF selectors more robust against changing layouts, adding a “banner-text” value for the HTML class attribute that will be associated with the message in a banner for the following banner components:
- ErrorNotification.vue
- WarningNotification.vue
- SuccessNotification.vue
- InfoNotification.vue
This issue is linked to [taf/BI-1014](https://github.com/Breeding-Insight/taf/pull/5)
=> [BI-1014] - Banner Class Modifications

src/breeding-insight/dao/ObservationDAO.ts, src/breeding-insight/dao/ObservationUnitDAO.ts, src/breeding-insight/dao/StudyDAO.ts, src/breeding-insight/dao/TrialDAO.ts, src/breeding-insight/model/Observation.ts, src/breeding-insight/model/ObservationUnit.ts, src/breeding-insight/model/Study.ts, src/breeding-insight/service/ObservationService.ts, src/breeding-insight/service/StudyService.ts, src/breeding-insight/service/TrialService.ts, src/components/observations/ObservationsListTable.vue, src/components/trials/StudiesListTable.vue, src/components/trials/StudyDetailPanel.vue, src/router/index.ts, src/views/observations/ObservationsList.vue
models and dao necessary for getting observationLevel value for an observation are in place. The changes needed in the ObservationService to pull the level value for each observation are left as a TODO.
=> BI-751 Create an interface to view an individual study and any observation data that’s been collected

src/breeding-insight/dao/TraitDAO.ts, src/breeding-insight/model/Trait.ts, src/breeding-insight/service/TraitService.ts, src/components/forms/TagField.vue, src/components/trait/TraitDetailPanel.vue, src/components/trait/TraitImportTemplateMessageBox.vue, src/components/trait/TraitListsTable.vue, src/components/trait/forms/BaseTraitForm.vue
- Adds tags to:
- New trait form
- Trait detail panel
- Trait edit panel
- Trait import
See other PRs for this feature:
brapi: https://github.com/Breeding-Insight/brapi/pull/40
bi-api: https://github.com/Breeding-Insight/bi-api/pull/95
sgn: https://github.com/Breeding-Insight/sgn/pull/30
Screen shots:
=> [BI-998] - Add tags to traits

src/breeding-insight/model/errors/ValidationError.ts, src/components/trait/TraitImportTemplateMessageBox.vue, src/components/trait/forms/BaseTraitForm.vue, src/components/trait/forms/CategoryTraitForm.vue, src/components/trait/forms/LabelValueRow.vue
Changes the scale categories README description to say `<value of the category> = <label of the category>` instead of `<label of the category> = <meaning of the category>`.
Changes to the UI:
- Switch the label and value around. The UI will look the same, values are just assigned differently to the scale model.
- Changes for switching between nominal and ordinal:
- When switching from ordinal to nominal, the category value is set equal to the previous category label. 
- When switching from nominal to ordinal, the category label is set equal to the category value.
- These changes were made to mimic the previous behavior on the UI. 
- Cleared the server validations for categories in the front end when switching between nominal and ordinal
- The validations were confusing because the errors …
=> [BI-1039] Switch label and value in scale categories

src/assets/scss/main.scss, src/components/tables/PaginationControls.vue, tests/unit/components/tables/ExpandableRowTable.spec.ts, tests/unit/components/tables/ExpandableTable.spec.ts, tests/unit/components/tables/SidePanelTable.spec.ts
By default HTML <a> elements with NO href attribute are not focusable. As the “Show All” button presently is such an element, it can’t be accessed by tabbing. 
- Make “Show All” accessible to tabbing by changing element to `<button>` (which is focusable). 
- For sake of consistency, change Next and Previous `<a>` elements to `<button>`.
- Updated unit tests to look for `<button>` instead of `<a>`
=> [BI-1087] "Show All" link on tables not focusable via tabbing

src/components/file-import/FileSelectMessageBox.vue, src/views/trait/TraitsImport.vue
Parses 400 errors on the front end to display a cleaner error message. Only 400 errors are parsed. If the error is not a 400 error, and not a `ValidationError`, a generic "An unknown error has occurred" message is shown.
=> [BI-1079] Parse 400 errors for trait import errors

src/components/admin/AdminUsersTable.vue, src/components/forms/BasicSelectField.vue
The current messages when a sys admin modifies their own role and no other fields are confusing. To simplify this, the field for modifying a user's role will be disabled when the user is the same as the sys admin.
**Changes:**
When user matches active user:
- In edit for System Users table, disabled Role field
- Only submitted change via promises for user info and not for user roles
- Use more specific user info success message 'User info (name/email/program) successfully updated'
Modified banner message logic for one promise succeeding and not the other to only fire when there are two promises
Linked to PR [taf/BI-640](https://github.com/Breeding-Insight/taf/pull/15)
=> [BI-640] - Disable modification of user role for self

src/breeding-insight/service/ProgramService.ts
Added check and error message to prevent creating programs with the same name.
This error message takes priority over the "BrAPI URL specified is not supported" error.
Connected to PR [bi-api/BI-975](https://github.com/Breeding-Insight/bi-api/pull/101)
=> [BI-975] - Prevent creating programs with same name

package.json, src/breeding-insight/service/TraitUploadService.ts, src/components/trait/TraitsImportTable.vue, src/views/trait/TraitsImport.vue, tests/unit/components/tables/SidePanelTable.spec.ts
Ontology Changes 
- Replace "Trait" with "Ontology" in Trait Import
- Alter table columns in Trait Import according to specifications
- Changed "traits" to "ontology terms" in modal message and banner messages
Linked to PR [taf/BI-997](https://github.com/Breeding-Insight/taf/pull/21) 
Redo of PR [bi-web/BI-997](https://github.com/Breeding-Insight/bi-web/pull/116)
=> [BI-997 BI-1061]-2 Update Trait Import (clean redo)

src/components/layouts/UserSideBarLayout.vue, src/components/trait/TraitListsTable.vue, src/views/trait/TraitsList.vue
Modified sidebar menu to use Ontology instead of Traits
Changed existing traits list to an ontology list and changed table and associated buttons to match desired UI
Linked to PR [taf/BI-994](https://github.com/Breeding-Insight/taf/pull/26)
=> [BI-994] Ontology UI - Review Existing Terms

src/breeding-insight/dao/ImportDAO.ts, src/breeding-insight/service/ImportService.ts, src/components/trait/ConfirmImportMessageBox.vue, src/views/import/ImportGermplasm.vue, src/views/import/ImportTemplate.vue, src/views/trait/TraitsImport.vue
- Execute ImportControllerIntegrationTest.sql on bidb to create test germplasm mapping
- Based off Trait Import 
- Uses indeterminate progress bar, could switch to brapi importer progress bar
- Importer endpoint calls embedded directly in ImportTemplate
- If want to reuse with trait import could use events and props and mixins but interface would be messier
- Will need some error handling testing / robustness probably in future cards related to this
=> [BI-1175] Extend GermplasmImport.vue to perform basic file import functionality

src/assets/scss/main.scss, src/components/forms/DataForm.vue
Notification messages were too short (height).
Pressing "Save" or "Cancel" now closes notification.
=> [BI-760-1] fixed bugs found in QA.

src/components/trait/ConfirmImportMessageBox.vue, src/views/import/ImportGermplasm.vue, src/views/import/ImportTemplate.vue, src/views/trait/TraitsImport.vue
- For both Germplasm and Trait Import, on clicking the "Confirm" button, the button will be disabled and a loading indicator will appear.
- (Changes were applied to Germplasm Import because both Traits and Germplasm Import use the  ConfirmImportMessageBox.vue component with the aforementioned "Confirm" button)
=> [BI-503] Add a loading indicator for Confirm Traits

src/breeding-insight/model/Trait.ts
see https://breedinginsight.atlassian.net/browse/BI-1249
I noticed that Synonyms was having the same problem and for the same reason, so I fixed that as well.
=> [BI-1249] Tags - Saving after <Cancel>

src/breeding-insight/dao/ObservationDAO.ts
Just put a large pageSize in the request from the ObservationDAO for now since the sorting and paging is done on the front end and we don't yet have the brapi sorting stuff implemented on the backend.
=> [BI-1171] Observation Pagination not working for programs using BB

src/views/trait/TraitsImport.vue
**Story:** [Ontology Import Success Banner Not Displaying](https://breedinginsight.atlassian.net/browse/BI-1282)
Due to recent changes to make notifications more transient, the ontology import success banner was not displaying as the call to emit it being made before the router redirect back to the Ontology list. The call has now been moved to after the redirect.
- [taf/BI-1260](https://github.com/Breeding-Insight/taf/pull/38) (in order to run ontology import scenarios with correctly updated files in TAF)
- Import valid import file (ie [test_import-xls.xls](https://github.com/Breeding-Insight/taf/blob/14cf50c504715ecbe53a913a7cda483c49ed0945/src/files/TraitImport/test_import-xls.xls))
- Click "Confirm"
- Banner “Imported ontology terms have been added to {program name}“.  should display …
=> [BI-1282] - Ontology Import Success Banner Not Displaying

src/views/import/ImportGermplasm.vue
**Story:** (https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1219)
Changes Parent DB ID references to Parent GID. There was no references on the UI. In the import germplasm table the parents are under "Pedigree". Only the import template needed to be changed. 
biapi: BI-1219 (https://github.com/Breeding-Insight/bi-api/pull/132)
1. This file with import germplasm into your brapi system:
[BI-1219_few_germplasm_in_file_parents.xls](https://github.com/Breeding-Insight/bi-web/files/7822894/BI-1219_few_germplasm_in_file_parents.xls)
2. This file will make GID references to those germplasm you just imported: 
[BI-1219_few_germplasm_db_parents.xls](https://github.com/Breeding-Insight/bi-web/files/7822901/BI-1219_few_germplasm_db_parents.xls) …
=> [BI-1219] Changing Parent DB ID to Parent GID

src/components/trait/TraitDetailPanel.vue
**Story:** [BI-1253 - ISSUE - Ordinal scale class label and value are swapped on UI - details view](https://breedinginsight.atlassian.net/browse/BI-1253)
Logic fix to display value followed by label in ordinal scale list in ontology details side panel.
- n/a
- Create single ontology term with ordinal scale, open details panel, check that the value is followed by label in list.
- Import file with ontology term with ordinal scale (ie https://github.com/Breeding-Insight/taf/blob/main/src/files/TraitImport/test_import-csv.csv), open details panel in preview table, check that the value is followed by label in list. Finish import, check the details panel again.
- [n/a] I have create/modified unit tests to cover this change
- [n/a] I have commented my code, particularly in hard-to-understand …
=> [BI-1253] - Ordinal Label Value Swap Details View

src/components/layouts/UserSideBarLayout.vue, src/router/index.ts, src/views/import/ImportExperiment.vue, src/views/import/ImportFile.vue
Adds a stub out of the experimental import. 
develop on bi-api
Go to the experimental import page. Download the template and verify.
Ran TAF and results were the same as result on develop (https://github.com/Breeding-Insight/taf/suites/5050389765/artifacts/149608412).
One test failed in the full run, so ran it by itself and it worked fine. Reports below.
[taf-bi-1145-1.pdf](https://github.com/Breeding-Insight/bi-web/files/7937080/taf-bi-1145-1.pdf)
[taf-bi-1145.pdf](https://github.com/Breeding-Insight/bi-web/files/7937081/taf-bi-1145.pdf)
=> [BI-1145] Add experiment import stub out

src/breeding-insight/model/import/ImportObjectState.ts, src/components/tables/expandableTable/ExpandableTable.vue, src/views/import/ImportGermplasm.vue, src/views/import/ImportTemplate.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1149
- Refactored germplasm import table to use the ExpandableTable. 
- Added highlighting and alert icon on duplicate rows. 
- Fixed a bug with the ExpandableTable where an error was thrown in the table was given data on initialization. 
- Added front end pagination to the ImportTemplate component. 
I am planning to run TAF before merging. 
bi-api: BI-1149 (https://github.com/Breeding-Insight/bi-api/pull/137)
All tests that pass in develop taf (https://github.com/Breeding-Insight/taf/suites/5064590044/artifacts/150443801) pass in TAF for this work. 
[taf-bi-1149.pdf](https://github.com/Breeding-Insight/bi-web/files/7943205/taf-bi-1149.pdf)
1. Import the in file duplicates …
=> [BI-1149] Highlighting duplicate germplasm

src/views/import/ImportGermplasm.vue
**Story:**[ ISSUE: Germplasm Import Template README still references DBID instead of GID](https://breedinginsight.atlassian.net/browse/BI-1338)
Replaced remaining instances of DBID with GID in README.
bi-api-develop
Go to germplasm import, download template, look at readme. All instances of DBID should be replaced with GID.
- [n/a] I have create/modified unit tests to cover this change
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to documentation
=> [BI-1338] - Germplasm Import Template references DBID instead of GID

src/breeding-insight/model/Sort.ts, src/components/ontology/OntologyTable.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1370
Made the trait description (Trait) sortable in the ontology table. 
bi-api: BI-1370
Here is a file to get some traits in your system if you need them. 
[BI_1373_good_traits.xls](https://github.com/Breeding-Insight/bi-web/files/8089813/BI_1373_good_traits.xls)
=> [BI-1370] ontology table: add trait description sorting

src/components/trait/TraitDetailPanel.vue
**Story:** [Improve ontology term snapshot](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1289)
Description and Synonyms labels were added to the trait details panel.
bi-api `develop` branch
verify labels exist when viewing detail panel
=> [BI-1289] add Description and Synonyms labels to detail panel

src/components/ontology/OntologyTable.vue, src/components/ontology/OntologyTable.vue.js, src/components/trait/TraitsImportTable.vue
[BI-1288](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1288)
Active and archived ontology lists as well as ontology import preview tables updated to show trait columns as entity + attribute.
bi-api `develop`
=> [BI-1288] Trait column on Ontology List page should be concatenation of trait entity + attribute

src/breeding-insight/service/UserService.ts, src/components/program/ProgramUsersTable.vue, src/store/sorting/getters.ts
**Story:** [BI-1369](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1369)
- Backend sorting enabled for roles column of program user's table
- Vuex sort module getter for program users updated to include roles
release/0.5 bi-api
backend code for sorting on user roles already in place, so only front-end changes
1. add several users of different roles and click on roles header to toggle sort order
2. navigate to locations tab and back to users tab and verify that sort state for users table has not changed
=> [BI-1369] enable backend sorting for roles column of program users table

src/breeding-insight/model/Sort.ts, src/components/ontology/OntologyTable.vue, src/components/trait/TraitsImportTable.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1372
Fix previous error with sorting (mistook trait description for entity + attribute in previous bug fix). 
Added `Trait` column sorting to import preview. 
biapi: BI-1372
See bi-api PR.
=> [BI-1372] Add ontology sort option for entity + attribute

src/breeding-insight/service/ImportService.ts, src/components/file-import/FileSelectMessageBox.vue, src/components/file-import/MultipleErrors.vue, src/views/import/BrAPIImporter.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1386
Displayed multiple error responses in the brapi importer. 
Put the multiple errors element into a component and shifted some code around to reuse formatting code. 
bi-api: BI-1386
See bi-api PR for testing instructions.
=> [BI-1386] Brapi importer: fix phenotyping importer

src/views/program/ProgramSelection.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1425
Updated the styling of the buttons on the program selection page so that the buttons don't use flexbox.  The desired look of the page was to have a button for each program on its own line.  The styling that was implemented accomplished this, but for some reason, caused the buttons to grow exponentially wide as more programs were added to the system.  The fix removes the use of flexbox for how these buttons display, and instead they are now just displayed as `block` elements.
bi-api: `release/0.5`
1. Add 5 or more programs to BI
2. In the browser URL bar, change the URL to the root (ex: `localhost:8080/admin/program-management` should be changed to `localhost:8080`)
3. Verify that the list of program buttons does not extend …
=> BI-1425 - Bad Scaling: Welcome BI Admin

package.json, src/breeding-insight/model/errors/ValidationError.ts, src/components/ontology/OntologyTable.vue, src/components/trait/TraitDetailPanel.vue, src/components/trait/forms/BaseTraitForm.vue, src/components/trait/forms/CategoryTraitForm.vue
**Story:** [ISSUE: New/Edit Term - Switching between scale classes, specifically ordinal and nominal, not working properly](https://breedinginsight.atlassian.net/browse/BI-1356)
Refactoring of Ordinal/Nominal display to get rid of anti-pattern, fix problem with ordinal/nominal category fields not displaying on first selection, and make code more robust.
- Functionality for modifying category "data" prop was moved from child component CategoryTraitForm.vue to parent component BaseTraitForm in order to avoid anti-pattern problems.
- Categories are now being passed in as categories (which is set to this.trait.scale.categories) due to the nested this.trait.scale.categories prop messing with reactivity
- Switching between ordinal/nominal now effectively hides the "value" fields rather than …
=> [BI-1356] Ordinal Nominal Switching Errors

src/components/ontology/OntologyTable.vue, src/components/tables/SidePanelTable.vue, src/components/tables/expandableTable/ExpandableTable.vue
**Story:** [BI-1414 - Improve table loading message](https://breedinginsight.atlassian.net/browse/BI-1414)
Updated both SidePanelTable.vue and ExpandableTable.vue to take in a loading prop and use it for logic re: displaying a no entries message.
bi-web/develop
- Open Ontology Table with no entries - no entries message displays only after loading complete
- Open Ontology Table with entries - no entries message never displays
- Open Germplasm Table with no entries - no entries message displays only after loading complete
- Open Germplasm Table with entries - no entries message never displays
- [n/a] I have create/modified unit tests to cover this change
- [n/a] I have commented my code, particularly in hard-to-understand areas
- [n/a] I have made corresponding changes to documentation
=> [BI-1414] - Improve table loading message

src/assets/scss/main.scss, src/components/ontology/OntologyTable.vue, src/components/tables/SidePanelTable.vue
**Story:** [BI-1404](https://breedinginsight.atlassian.net/browse/BI-1404?atlOrigin=eyJpIjoiNjdlZjFhNjU0M2UwNDZkNWEyM2M0MzZhOTRiMmRhNzYiLCJwIjoiaiJ9)
- Added loading indicator to sidepanel table
- Set loading prop in ontology table
- develop on bi-api
- Test loading with breedbase which is slower and verify indicator shows
=> BI-1404 - No loading wheel ontology page

src/breeding-insight/dao/SharedOntologyDAO.ts, src/breeding-insight/model/SharedProgram.ts, src/breeding-insight/model/SharedProgramRequest.ts, src/breeding-insight/service/SharedOntologyService.ts, src/breeding-insight/service/ValidationErrorService.ts, src/components/modals/GenericModal.vue, src/components/program/SharedOntologyConfiguration.vue, src/router/index.ts, src/views/program/ProgramConfiguration.vue, src/views/program/ProgramManagement.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1363
- Added a Program Configuration page
- Create a Shared Ontology component
- Handled errors coming back from the shared ontology endpoints. 
biapi: BI-1363
See biapi PR for testing details, https://github.com/Breeding-Insight/bi-api/pull/166.
=> [BI-1363] Program Configuration and Share Ontologies

.env.development, src/breeding-insight/dao/GermplasmDAO.ts, src/breeding-insight/service/GermplasmService.ts, src/breeding-insight/utils/GermplasmUtils.ts, src/router/index.ts, src/views/germplasm/GermplasmDetails.vue, src/views/germplasm/GermplasmTable.vue
**Story:** [BI-1339 - Germplasm Details page](https://breedinginsight.atlassian.net/browse/BI-1339)
Updates to enable display of individual germplasm details
- Added GermplasmDetails.vue to display individual germplasm information
- Updated GermplasmTable.vue to include a column with links to germplasm details for each germplasm and to retrieve the germplasm UUID for use in said link
- Added reference source to .env.development to aid in retrieval of germplasm UUID from external references on front end
- Added api call to new /programs/${programId}/brapi/v2/germplasm/${germplasmId} endpoint to retrieve individual germplasm information
- Updated router to include navigation to germplasm details page
[bi-api/feature/BI-1339](https://github.com/Breeding-Insight/bi-api/pull/176)
1. Import …
=> [BI-1339] Germplasm Details page

src/components/program/SharedOntologyConfiguration.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1363
For the share ontology modal, the 'Save' button was disabled while saving, but not the 'Cancel' button. I add the disable logic to the 'Cancel' button as well. 
NOTE: Based off `bug/BI-1366` so includes some of those changes. 
biapi: develop
1. Set a debug point in biapi inside the `/programs/{programId}/ontology/shared/programs` endpoint. 
2. Share ontology with another program
3. The debug point will pause the backend so you can see the button state. 
4. Check that the save button has a loading wheel and that both the save and cancel buttons are disabled.
=> [BI-1363] Disable cancel button on share ontology save

src/assets/scss/main.scss, src/breeding-insight/service/TraitService.ts, src/components/ontology/OntologyTable.vue, src/components/trait/TraitDetailPanel.vue
**Story:** [BI-1445 - Trait Column value not the same as entered in the the Term creation](https://breedinginsight.atlassian.net/browse/BI-1445)
Implemented changes to make capitalization of trait entity, trait attribute, and method description more consistent in table and sidepanel display.
For display in table and details panel, the first letter of each word for the trait entity, trait attribute, and method description will be capitalized
For trait attribute and method description the rest of the capitalization will match what the user entered, and on edit the user will see the capitalization as they entered it.
For trait entity, due to it being a set and therefore having to have consistent case, regardless of user entry for capitalization the first letter of each word will always be …
=> [BI-1445] - Trait Entity/Attribute/Method capitalization

src/components/germplasm/GermplasmListsTable.vue
**Story:** [BI-1224 - Show list creator in Germplasm lists table](https://breedinginsight.atlassian.net/browse/BI-1224)
Retrieves list creator and displays for germplasm lists.
Added Created By column in Germplasm Lists table that takes in listOwnerName
Changed Date Created to Created Date to be more consistent with other tables
[bi-api/BI-1224](https://github.com/Breeding-Insight/bi-api/pull/194)
For breedbase and brapi test server:
- Import germplasm under two different users
- Go to germplasm list table
- Created By column should exist
- Column should display name of correct user that imported germplasm list
=> [BI-1224] - Show list creator in Germplasm lists table

src/assets/scss/main.scss, src/breeding-insight/model/FileType.ts, src/components/germplasm/GermplasmListsTable.vue, src/components/modals/SelectModal.vue
**Story:** [BI-1199 - Choose file format for germplasm export](https://breedinginsight.atlassian.net/browse/BI-1199)
Changes to frontend to enable modal selection of file type when downloading germplasm list and passing of user selection to backend.
Added new reusable modal component SelectModal that takes in title and a list of options to display, and utilized it to display file types upon user clicking download and pass that information on click.
[bi-api/BI-1199](https://github.com/Breeding-Insight/bi-api/pull/193)
- Open Germplasm List
- Click Download
- Verify modal pops up and shows
- Verify each file type can be selected
- Verify when cancel clicked the modal closes and nothing is downloaded
- Verify for each file type (csv, xls, xlsx) that when it is selected and download is …
=> [BI-1199] - Choose file format for germplasm export

src/assets/scss/main.scss, src/components/ontology/OntologyTable.vue, src/views/germplasm/Germplasm.vue, src/views/ontology/Ontology.vue
**Story:** [BI-1499 - Improve Presentation of Buttons](https://breedinginsight.atlassian.net/browse/BI-1499)
Added Batch Import button to Germplasm page above tabs.
Moved Batch Import button to Ontology page above tabs
bi-api/develop
For Germplasm Page
- Import Batch File button should be present above the tabs
- Clicking said button should lead to Germplasm Import page
For Ontology Page
- Import Batch File button should be present above the tabs
- New Term should still be below tabs as before
- Clicking Import Batch File should lead to Ontology Import page
=> [BI-1499] - Improve Presentation of Buttons

src/assets/scss/main.scss, src/breeding-insight/utils/CallStack.ts, src/components/tables/expandableTable/ExpandableTable.vue, src/views/germplasm/GermplasmTable.vue
**Story:** https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1191
- Added filtering support to ExpandableTable.
- Added filtering to Germplasm Table. 
- Modify table loading behavior so only table rows were greyed out and user can still interact with filter fields. 
- Added a `CallStack` class that could be a good replacement for current pagination request behavior. 
biapi: BI-1191
See biapi PR.
=> [BI-1191] Germplasm Search

src/views/import/ImportExperiment.vue
**Story:** 
1146 failed QA. The failure was `Acceptance 1. The experiment import template still has a column for “Exp Trt Factor Name” instead of “Treatment Factors”.`
Updated template.  Updated display column name
bi-api branch bug/BI-1146
1.  Download and use new template.
2. Insure that the the column name in the template and READ ME is **Treatment Factors** and not **Exp Trt Factor Name**
3. Insure that the column on the table on the summary screen reads  **Treatment Factors** and not **Exp Trt Factor Name**
=> [BI-1146] change ‘Exp Trt Factor Name’ to ‘Treatment Factors’ - failed QA

src/assets/scss/main.scss, src/breeding-insight/dao/TrialDAO.ts, src/breeding-insight/service/TrialService.ts, src/components/experiments/ExperimentsObservationsTable.vue, src/components/layouts/UserSideBarLayout.vue, src/router/index.ts, src/views/experiments-and-observations/ExperimentsAndObservations.vue
**Story:** [BI-1198 - All Experiments Table](https://breedinginsight.atlassian.net/browse/BI-1198)
Created Experiments and Observations Table
- Added ExperimentsAndObservations.vue and ExperimentsObservationsTable.vue component to display experiment information (download link and date created/created by to be implemented fully in future cards)
- Included a button on ExperimentsAndObservations to link to experiment import
- Modified UserSideBarLayout.vue and router/index.ts to redirect to ExperimentObservations.vue instead of Trials and Studies
- Added fixed-width-wrapped to main.scss to constrain title and dataset column width
- Modified TrialDAO.ts and TrialService.ts to pass in metadata parameter
**NOTE**
Presently this means the original Trials and Studies table components are no …
=> [BI-1198] All Experiments Table

src/views/import/ImportExperiment.vue
added Experimental Unit to summary.  Hide redundant Experiment details in the Table
[BI-1189](https://breedinginsight.atlassian.net/browse/BI-1189) failed QA.  _Experimental Unit_ data needs to be added to the summary on  the confirmation page for Experiment Import(above the table).
Also the redundant experiment details needs to be removed from the table.  The columns to be removed are:
- Experiment Title
- Experiment Description
- Experiment Unit
- Experiment Type
bi-api branch develop
1. Import _Experiments and Observations_ data from a flat file (you should now be on the confirmation page).
2. The _Experimental Unit_ should appear in the summary section (under **Experiment**)
3. In the table below, you should not see the columns "Experiment Title", "Experiment Description", Experiment …
=> BI-1189 failed QA - Added Experimental Unit to summary.

src/views/germplasm/GermplasmTable.vue
**Story:** [BI-1506 - "Created Date" field in the All Germplasm table has the wrong date format.](https://breedinginsight.atlassian.net/browse/BI-1506)
Changed Created Date column in Germplasm Table to use GermplasmUtils.getCreatedDate like in the Germplasm Details page so date formatting is consistent.
bi-api/develop
Open germplasm table
Ensure "Created Date" is in YYYY-MM-DD format
=> [BI-1506] Fix "Created Date" format for Germplasm table

src/components/germplasm/GermplasmListsTable.vue
**Story:** [BI-1506 - "Created Date" field in the All Germplasm table has the wrong date format.](https://breedinginsight.atlassian.net/browse/BI-1506)
Germplasm Lists Table updated to be in the proper YYYY-MM-DD format.
bi-api/develop
- Open Germplasm Lists table
- Ensure Date Created in YYYY-MM-DD format
=> [BI-1506] Fix date for Germplasm Lists Table

src/breeding-insight/model/import/germplasm/Pedigree.ts, src/components/germplasm/GermplasmPedigreesView.vue, src/views/germplasm/GermplasmDetails.vue, src/views/germplasm/GermplasmTable.vue, src/views/import/ImportGermplasm.vue
**Story:** [BI-1230 - Truly Unknown Germplasm](https://breedinginsight.atlassian.net/browse/BI-1230)
Updates to support importing germplasm with truly unknown parents without using a dummy parent. This development also ensures that unrelated germplasm with unknown parents are not falsely attributed as siblings in the pedigree view display.
To import a file with unknown parents, a GID or entry number of 0 must be used. Presently only both parents unknown or female parent known and male parent unknown are supported. 
Unknown parents will be displayed as "Unknown" in the parent GID columns in the All Germplasm table and in the pedigree in Germplasm Details page.
Due to Breedbase limitations, parents with more than 10 progeny will cause the pedigree viewer to error (to be fixed in BI-1579. …
=> [BI-1230] Truly Unknown Germplasm

src/breeding-insight/model/Sort.ts, src/views/germplasm/GermplasmTable.vue
**Story:**  [BI-1478 - Add Pedigree to All Germplasm Table](https://breedinginsight.atlassian.net/browse/BI-1478)
Added pedigree column to All Germplasm table that displays the parent names with searching (but NOT sorting) enabled.
[bi-api/feature/BI-1478](https://github.com/Breeding-Insight/bi-api/pull/213)
- Open All Germplasm Table
- Check that Pedigree column exists
- Check that entries with parent GIDs have pedigree with corresponding parents in Pedigree Column
- Check that Pedigree column not sortable
- Try searching in Pedigree column for several different search terms
=> [BI-1478] - Add Pedigree to All Germplasm Table

src/breeding-insight/service/BrAPIService.ts
**Story:** [BI-1589 - All Germplasm table pagination doesn't work with page-1 or show-all](https://breedinginsight.atlassian.net/browse/BI-1589)
All Germplasm table pagination logic uses 0-indexing to comply with BrAPI, which was leading to some pagination problems due to 0 being treated as falsy in javascript. This added a fix to handle that.
bi-api/develop
- In the "All Germplasm" table, change page size to have multiple pages
- Click on a page that is not page 1
- Click on page 1, pagination and results should return to page 1
- Click on page 2
- Click previous button, pagination and results should return to page 1
- Click on a page that is not page 1
- Click show-all, all entries should appear
=> [BI-1589] - Germplasm pagination doesn't work with page-1 or show-all

src/components/forms/BasicInputField.vue, src/components/forms/BasicSelectField.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1585
Updated `BasicSelectField` to replace all occurances of a space with a dash.  Bug was that only the first instance of a space was being replaced.  Also updated both `BasicSelectField` and `BasicInputField` to strip out non-alphanumeric and dash characters from the `id` field.
1. Share a program's ontology with another program
2. Navigate to the program that an ontology was shared with
3. Navigate to the program configuration page
4. Inspect the `select` input's ID, and verify that it is "Choose-ontology-to-subscribe-to"
=> BI-1585 - TAF - Set proper id for "Choose ontology to subscribe to:" drop-down

src/assets/scss/main.scss, src/views/import/ImportExperiment.vue
**Story:** [BI-1147](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1147)
a class was added to the germplasm names in new experiment import preview so that it can be styled light purple.
created by/date fields in experiment details of the preview are only displayed if importing into an existing experiment.
bi-api BI-1147 branch
create a new experiment and verify preview summary and table match the wireframe.
import the same data with a different environment and verify that createdBy and createdDate fields are diplayed in preview summary.
=> [BI-1147] ﻿﻿2.0 Experimental Data Preview Universal Elements

src/views/germplasm/GermplasmTable.vue
[BI-1634 (Germplasm filtering and sorting fails for pages beyond the first)](https://breedinginsight.atlassian.net/browse/BI-1634)
bi_api: release/0.7
1. Go to an All Germplasm table with more than one page.
2. Go to any page other than page-1.
3. Apply a valid filter to any column.
**Expected Result**
1. Valid filtered Germplasm table should displayed
2. The Germplasm table should be on page-1
=> [BI-1634] When filtering the list, set the page to page-1

src/views/import/ImportExperiment.vue, src/views/import/ImportTemplate.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1653?atlOrigin=eyJpIjoiZDc3NjY3ZDkyNzFkNDdkZWIxYjk3ODZkNjI0NmUyNjEiLCJwIjoiaiJ9
- Added displaying phenotype columns to import preview table
- bi-api feature/BI-1653
- Import experiment files with and without phenotype observations and verify preview table matches file
=> BI-1653 - Update Experiment Preview to show observations

src/breeding-insight/model/Observation.ts, src/breeding-insight/model/import/ImportPreview.ts, src/views/import/ImportExperiment.vue, src/views/import/ImportTemplate.vue
**Story:** [BI-1194 - Upload with timestamps](https://breedinginsight.atlassian.net/browse/BI-1194)
Updates to enable display of timestamp values in experiment import preview and to ensure that dynamic columns (phenotypes and timestamps) are displayed in the same order as in the import file.
[bi-api/BI-1194](https://github.com/Breeding-Insight/bi-api/pull/225)
- Import experiment file with phenotypes and timestamps of both date and date/time values (the latter indicated by TS: ontology term name)
- Ensure preview screen displays phenotype and timestamp columns and values in same order as file
- Ensure timestamp columns with date only in file also have time of midnight associated in preview
- Import experiment file with incorrect timestamp format - error should display
- Import experiment …
=> [BI-1194] - Upload with timestamps

src/breeding-insight/model/Sort.ts, src/breeding-insight/model/Trait.ts, src/breeding-insight/model/TraitSelector.ts, src/components/ontology/OntologyTable.vue, src/components/trait/TraitDetailPanel.vue, src/components/trait/forms/BaseTraitForm.vue
**Story:** [BI-1614 - Add Term Type to Ontology Term display and form creation/modification](https://breedinginsight.atlassian.net/browse/BI-1614)
Added TermType enum and added dropdown to select Term Type in ontology term form.
Added display of term type in ontology side panel and ontology table
bi-api/develop
NOTE: As Term Type is not yet stored in backend, table/side panel display will need to be tested in [BI-1615](https://github.com/Breeding-Insight/bi-web/pull/285)
- Navigate to ontology table
- Should see empty Term Type column
- Select new term
- New input Term Type should be present at top of form, with a dropdown and "Phenotype" selected as default.
- Dropdown should list the options "Phenotype", "Germplasm Attribute", and "Germplasm Passport"
- User should be able to select …
=> [BI-1614] - Add Term Type to Ontology Term display and form

src/breeding-insight/model/Sort.ts, src/breeding-insight/service/BrAPIService.ts, src/components/experiments/ExperimentsObservationsTable.vue, src/store/sorting/getters.ts, src/store/sorting/index.ts, src/store/sorting/mutation-types.ts, src/store/sorting/mutations.ts, src/store/sorting/types.ts, src/views/experiments-and-observations/ExperimentsAndObservations.vue
**Story:** [BI-1477 - Improve Experiments Table](https://breedinginsight.atlassian.net/browse/BI-1477)
Updated Experiments Table and relevant getters/mutators/etc to enable backend sortable/filtering columns and make the Names column sortable and filterable and the Status column sortable.
[bi-api/BI-1477](https://github.com/Breeding-Insight/bi-api/pull/230/files)
- Open Experiments and Observations table
- Check that experiments display
- Check that both the Name and Status columns can be sorted
- Check that the Name column can be filtered
- Check that sorting and filtering works with pagination
=> [BI-1477] - Improve Experiments Table

src/breeding-insight/model/Trait.ts, src/breeding-insight/model/TraitSelector.ts, src/breeding-insight/utils/EnumUtils.ts, src/breeding-insight/utils/TraitStringFormatters.ts, src/components/ontology/OntologyTable.vue, src/components/trait/TraitDetailPanel.vue, src/components/trait/TraitsImportTable.vue, src/components/trait/forms/BaseTraitForm.vue, src/views/trait/TraitsImport.vue
**Story:** [BI-1613 - Add Term Type to Ontology Term Import](https://breedinginsight.atlassian.net/browse/BI-1613)
Updated Ontology Import Preview table to include Term Type column
Updated Ontology Import Template button to download updated template version
Note: This is branched off of BI-1615, so until that is merged the changelist will include changes from that branch
[bi-api/BI-1613](https://github.com/Breeding-Insight/bi-api/pull/233)
- Open Ontology Batch Import
- Click download template - ensure template downloaded is v13 and has term type column
- Create ontology import using download template with blank and filled values for term type with different casing
- Upload created file
- Check import preview table displays correct term types for user inputted rows
- Check import preview …
=> [BI-1613] - Add Term Type to Ontology Term Import

src/breeding-insight/model/Sort.ts, src/breeding-insight/model/Trait.ts, src/breeding-insight/model/TraitSelector.ts, src/breeding-insight/utils/EnumUtils.ts, src/breeding-insight/utils/TraitStringFormatters.ts, src/components/ontology/OntologyTable.vue, src/components/trait/TraitDetailPanel.vue, src/components/trait/forms/BaseTraitForm.vue
**Story:** [BI-1615 - Add termType to Trait DB Table](https://breedinginsight.atlassian.net/browse/BI-1615)
NOTE: This is forked from BI-1614, so changelist will include changes from there until BI-1614 is merged into develop
Small improvements off BI-1614 to ensure term types actually display
Created EnumUtils to handle methods for converting between enum key and value for ease of converting between the user-friendly display value and the backend storage value, and utilized them for term types
NOTE: Sorting could get weird if the alphabetical order differs between the user friendly display (ie Germplasm Passport) and backend storage value (GERM_PASSPORT). Not a problem here, but something to keep in mind. Also the difference between display and backend and the fact that there are a few …
=> [BI-1615] - Add termType to Trait DB Table

src/breeding-insight/model/Sort.ts, src/breeding-insight/service/BrAPIService.ts, src/components/germplasm/GermplasmListsTable.vue, src/components/germplasm/GermplasmTable.vue, src/store/sorting/getters.ts, src/store/sorting/index.ts, src/store/sorting/mutation-types.ts, src/store/sorting/mutations.ts, src/store/sorting/types.ts, src/views/germplasm/GermplasmLists.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1616?atlOrigin=eyJpIjoiMDY3MzAwZjNlNTM4NDQ4MzkwMmJhZDUzN2UxYjdmZWMiLCJwIjoiaiJ9
- Added support for filtering on brapi lists endpoint
- bi-web feature/[BI-1616](https://breedinginsight.atlassian.net/browse/BI-1616)
- Test filtering, sorting and pagination in Germplasm Lists table to verify it's working as expected.
[BI-1616]: https://breedinginsight.atlassian.net/browse/BI-1616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1616 - Add Filtering to Germplasm Lists Table

src/components/germplasm/GermplasmTable.vue
**Story:** [BI-1129](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1129)
When the filter state is updated for the germplasm table, the page is set to 1.
Go to an All Germplasm table with more than one page.
Go to any page other than page 1.
Apply a valid filter to any column.
Expected Result
Valid filtered Germplasm table should displayed
The Germplasm table should be on page 1
[BI-1129]: https://breedinginsight.atlassian.net/browse/BI-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1129] add fix for pagination bug

package-lock.json, package.json, src/assets/scss/main.scss, src/breeding-insight/dao/BreedingMethodDAO.ts, src/breeding-insight/model/BreedingMethod.ts, src/breeding-insight/service/BreedingMethodService.ts, src/components/layouts/ExpandableCard.vue, src/components/modals/BaseModal.vue, src/components/modals/GenericModal.vue, src/components/program/SharedOntologyConfiguration.vue, src/components/program/SubscribeOntologyConfiguration.vue, src/components/tables/expandableTable/ExpandableTable.vue, src/config/ability.ts, src/router/index.ts, src/views/germplasm/BreedingMethods.vue, src/views/program/OntologySharing.vue, src/views/program/ProgramManagement.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1651
Created a new interface under program administration to allow a breeding program to control what system breeding methods are allowed, and to create/edit/delete their own custom breeding methods.
bi-api/feature/BI-1651
1. Verify that only the `breeder` role can see the Breeding Method configuration screen
2. Verify that when first creating a program, and then navigating to the Breeding Method config screen, that all of the system breeding methods are visible
3. Verify that system breeding methods can be enabled/disabled
4. Verify that a new breeding method can be created, and that it only shows up for the program it was created in
5. Verify that germplasm can be created with program defined breeding methods
6. Verify that …
=> BI-1651 - Allow programs to choose/create breeding methods

src/breeding-insight/model/Sort.ts, src/components/experiments/ExperimentsObservationsTable.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1548?atlOrigin=eyJpIjoiMDU3NTE2YWExOTFlNGMxZWJlOTA2N2Y2YWRhOWY3NDYiLCJwIjoiaiJ9
- Added createdBy and createDate experiment filtering
- bi-api BI-1548
- Test sorting and filtering for experiments CreatedBy and createDate
=> BI-1548 - Experiments: User and Creation Date Refinement

src/components/experiments/ExperimentsObservationsTable.vue
**Story:** [BI-1477](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1477)
set page to first when exp name filter input updated
bi-api develop
1. load 11 or more experiments.
2. select any page except the first on exp&obs table.
3. enter a value for name filter
4. check that expected matches are displayed.
[BI-1477]: https://breedinginsight.atlassian.net/browse/BI-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1477] Bugfix:Improve All Experiments Table

src/breeding-insight/service/GermplasmService.ts, src/breeding-insight/utils/GermplasmUtils.ts, src/components/germplasm/GermplasmTable.vue, src/views/germplasm/GermplasmByList.vue
**Story:** [BI-1606](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1606)
The germplasm list details page now uses a helper function to display the entry number whether the number is stored using the old format of importEntryNumber or using the listEntryNumbers map.
bi-api feature/BI-1606 branch
1. Import germplasm with user-supplied entry numbers. 
2. Go to the Germpasm Lists tab and use the dev tools console to inspect the list object in the response and verify there is an external reference entry for /lists and note the UUID stored as the refernceID.
3. Then view all imported germplasm and use the dev tools console to inspect the germplasm objects in the response from bi-api. Verify the additionalInfo field "listEntryNumbers" …
=> [BI-1606] Allow germplasm records to be in multiple lists

src/breeding-insight/service/ProgramService.ts
[BI-1620](https://breedinginsight.atlassian.net/browse/BI-1620) Program Selection page doesn't show all programs if more than 50 exist
_Please include a summary of the change that was made._
Program Selection page now shows up to 1000-programs
br-api : develop branch
1.  GIVEN there are at least 50 active programs.
2. WHEN log in with a user-account that has at least 20 active programs (or the System Admin)
3. THEN on the Welcome screen, you should see all the programs listed( see screen capture below).
4. WHEN the user navigates to select a new program in the upper right hand corner (see screen capture below)
5. THEN all of the programs should be listed.
6.  GIVEN the user selects the 'Programs' menu option
7. THEN only the first 50 programs should be visible.
8. GIVEN the user select …
=> bug/BI-1620 - Program Selection page doesn't show all programs if more than 50 exist

src/components/germplasm/GermplasmGenotypeView.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1741
- Update display of genotypes (genotypes are now returned as text value instead of number value)
- Update Variant column name to Chromosome
bi-api bug/BI-1741
brapi bug/BI-1741
Mgdb2BrapiV2Impl bug/BI-1741
Test using instructions from [BI-1650](https://breedinginsight.atlassian.net/browse/BI-1650)
[BI-1650]: https://breedinginsight.atlassian.net/browse/BI-1650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1741 - Genotype Import

src/views/import/ImportExperiment.vue, src/views/import/ImportGermplasm.vue, src/views/trait/TraitsImport.vue
[BI-1583](https://breedinginsight.atlassian.net/browse/BI-1583) 
Updated URLs for the import templates for germplasm, ontology, and experiments.
bi-api branch feature/BI-1583
**GERMPLASM TEMPLATE**
1.  Navigate to the Import file screen
2. Click on the "germplasm" tab.
3. Click on the "Download the Germplasm Import Template" button
4. Inspect the downloaded xls file.
the _last_ sheet in the workbook should be titled "Data"
**ONTOLOGY TEMPLATE**
1.  Navigate to the Import file screen
2. Click on the "Ontology" tab.
3. Click on the "Download the Ontology Import Template" button
4. Inspect the downloaded xls file.
the _second_ sheet in the workbook should be titled "Data"
**EXPERIMENT & OBSERVATION TEMPLATE**
1.  Navigate to the Import file screen
2. Click on …
=> BI-1583 updated the direct links to the templates

src/router/index.ts, src/views/program/ProgramConfiguration.vue, src/views/program/ProgramManagement.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1707
Renamed Ontology Sharing tab to Configuration in Program Management.
Because this tab will eventually contain more than Ontology Sharing, I renamed the `OntologySharing` component to `ProgramConfiguration`.
I updated TAF to account for the changes, [TAF PR](https://github.com/Breeding-Insight/taf/pull/109). Should be merged concurrently.
If you want to run TAF locally, checkout the [feature/BI-1707 branch of TAF](https://github.com/Breeding-Insight/taf/tree/feature/BI-1707) and run TAF with `--tags @BI-1502` to test the Configuration feature.
=> [BI-1707] - renamed shared ontology to configuration

src/views/germplasm/BreedingMethods.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1779
Commented out code for enabling/disabling system breeding methods within a program.
bi-api/bug/BI-1779
- Log in to a program with a user that is a breeder in that program
- Navigate to Program Configuration
- Navigate to Breeding Methods
- Ensure that there is no button for "Choose Predefined Methods"
=> BI-1779 - Import germplasm with unspecified breeding method

src/breeding-insight/model/Sort.ts, src/components/tables/PaginationControls.vue, src/components/trait/TraitsImportTable.vue
**Story:** [BI-1617](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?modal=detail&selectedIssue=BI-1617)
`OntologySortField` enum was changed from methodDescription to methodHandle.
latest bi-api
[BI-1617]: https://breedinginsight.atlassian.net/browse/BI-1617?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1617 bug - sorting on ontology method is broken

src/components/experiments/ExperimentObservationsDownloadButton.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1238
This is not the main feature, it is a bugfix after the already-merged feature failed QA. The issue was the that first download button on a list view would open its modal and all the controls would work, but subsequent download buttons would open their modals and the toggle switch could not be toggled. This was due to duplicate id attributes.
I made the id attribute of inputs that may appear multiple times on the same page unique.
I created a new task on Jira for a further refactor that I'd like to do that is lower priority: https://breedinginsight.atlassian.net/browse/BI-1800.
You may want to check out the bi-api [feature/BI-1238](https://github.com/Breeding-Insight/bi-api/tree/feature/BI-1238) branch which has a dummy …
=> [BI-1238] - made ids unique

src/views/germplasm/BreedingMethods.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1805
Removed the warning message above the list view that was visible when there were Program-scoped Breeding Methods that were in use. 
Added an informational message at the top of each edit form for Program-scoped Breeding Methods that are in use. 
Only applies to Program-scoped Breeding Methods, so create some for Testing. Then, upload Germplasm using the abbreviation you defined in the Breeding Method column of the upload file. You should be able to see the informational message "Breeding method is in use. Deletion disabled." after expanding the edit view of a Program-scoped Breeding Method that is in use.
TAF coverage: https://github.com/Breeding-Insight/taf/pull/113
=> [BI-1805] - improved communication for in-use methods

src/components/file-import/FileSelectMessageBox.vue, src/components/file-import/MultipleErrors.vue, src/views/import/ImportTemplate.vue, src/views/trait/TraitsImport.vue
[BI-1618 ](https://breedinginsight.atlassian.net/browse/BI-1618)- Import File Selection Behavior
- To satisfy requirement 1 --  the button wording was changed in _FileSelectMessageBox.vue_
- To satisfy requirement 2 -- In _views/import/ImportTemplate.vue_ and _views/trait/TraitsImport.vue_ the ImportAction.RESET is called to set this.file to null.  
- To satisfy requirement 3 -- All import errors will now result in an error-banner on the top of the page (If the error-banner was appearing before this release, it will still appear, but with the improved verbiage.  If there was no error-banner before this release, now it will now appear, as well as the errors as they were previously presented)
**bi-api:**  feature/BI-1618
Import files into Germplasm, Ontology, and Experiments.  One file for …
=> Feature/bi 1618 - Import File Selection Behavior

src/breeding-insight/model/ActionMenuItem.ts, src/components/DownloadModal.vue, src/components/experiments/ExperimentObservationsDownloadModal.vue, src/components/experiments/ExperimentsObservationsTable.vue, src/components/layouts/menus/ActionMenu.vue, src/views/experiments-and-observations/ExperimentDetails.vue
**Story:** [BI-1821](https://breedinginsight.atlassian.net/browse/BI-1821?atlOrigin=eyJpIjoiNDRjODQ5MDZmNTQ3NDhkMjk3M2M1MmU4NjFkNWI1MDQiLCJwIjoiaiJ9)
- Added action menu component and replaced buttons with it on Experiment page
- Refactored ExperimentObservationsDownloadButton so that activation is outside the component and has dynamic reloading of study options and renamed to modal
- Refactored ExperimentObservationsTable so that there is one modal rather than one for each row in the table
- develop on bi-api
- Ensure download links in ExperimentObservationsTable work as before
- Ensure action menu items work as expected
[BI-1821]: https://breedinginsight.atlassian.net/browse/BI-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1821 - Experiment import/download buttons wrong color

src/components/germplasm/GermplasmTable.vue, src/components/tables/PaginationControls.vue, src/components/tables/expandableTable/ExpandableTable.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1799
I added a prop to `ExpandableTable` and `PaginationControls` to conditionally enable the "Show All" button. It defaults to `true`, I passed `false` in `GermlpasmTable` in order to disable it.
I made the default page size 200 in `GermplasmTable`.
Import a large Germplasm file, make sure the default page size on the Germplasm view is 200 and the "Show All" button is not available.
Also, ensure that the other tables that use `ExpandableTable` haven't been broken.
=> BI-1799 - Disable Germplasm Show All

src/assets/scss/main.scss, src/views/BrAPI/BrAPIInfo.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1872
- Updated the BrAPI page to use card components
- Added a card for generating an API token
bi-api/feature/BI-1872
A)
1. Log in to DeltaBreed
2. Navigate to a program
3. Navigate to the "BrAPI" page via the menu
4. click on "Generate Access Token"
5. Ensure that a new access token is generated and displayed with the expiration timestamp
B)
1. Generate an access token (test A)
2. Using that access token, make a REST call (via Insomnia/Postman): 
- header: `Authorization` and value of `Bearer <access token>`
- URL: `<program BrAPI URL>/germplasm` (grab the BrAPI base URL on the BrAPI page in DeltaBreed)
3. Ensure that the rest call returns back the germplasm for that program
=> BI-1872 - Generate Access Token for using BrAPI with DeltaBreed

src/breeding-insight/dao/GermplasmDAO.ts, src/util/ListType.ts, src/views/germplasm/GermplasmLists.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1845
Updated all GET calls to the /lists endpoint to include the `listType` parameter.
https://github.com/Breeding-Insight/bi-api/pull/284
Checkout the bi-api feature/BI-1845 branch as well for testing.
=> BI-1845 - add listType parameter to /lists GET calls

src/App.vue, src/views/import/ImportFile.vue, src/views/import/ImportTemplate.vue
**Story:** [BI-1876](https://breedinginsight.atlassian.net/browse/BI-1876?atlOrigin=eyJpIjoiNDFmYzAxMzY1MzBmNDY1NThkNjRkZmM5ZTg1NzI1ODIiLCJwIjoiaiJ9)
- Changed notification to warning and changed text
- bi-api bug/BI-1876-test
- This is just for testing purposes and will always throw a InternalServerExeption when confirming import
- Upload a germplasm file and on confirmation verify a warning message is displayed
[BI-1876]: https://breedinginsight.atlassian.net/browse/BI-1876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1876 - Generic Error on Successful Upload of Large Germplasm File

src/views/import/ImportTemplate.vue
**Story:** [BI-1900](https://breedinginsight.atlassian.net/browse/BI-1900) -  Exp error message improvement.
The _Error Messages Before Preview_ should be as described in the [source of truth](https://breedinginsight.atlassian.net/wiki/spaces/BI/pages/1673822352/Import+Validation+Errors+Warnings#Step-1:-Error-Messages-Before-Preview)
[BI-1900]: https://breedinginsight.atlassian.net/browse/BI-1900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1900 -  Exp error message improvement

src/views/import/Dataset.vue
**Story:**  [BI-1918](https://breedinginsight.atlassian.net/browse/BI-1918)
If there is an experiment with Observation Units but no observation variables, then when displaying the experiment, no Observation Units are displayed.
1. Import an experiment with Observation Units but no Observation Variables (traits).
2. Display the experiment.
**EXPECTED RESULT**
Withing the Observation Dataset tab, all of the Observation Units should be displayed.
[BI-1918]: https://breedinginsight.atlassian.net/browse/BI-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1918] Experiment: No datasets exist

package.json, src/breeding-insight/dao/ExperimentDAO.ts, src/breeding-insight/model/ObservationUnit.ts, src/breeding-insight/model/Sort.ts, src/breeding-insight/model/Study.ts, src/breeding-insight/service/BrAPIService.ts, src/breeding-insight/service/StudyService.ts, src/components/experiments/ExperimentsObservationsTable.vue, src/views/germplasm/BreedingMethods.vue, src/views/import/Dataset.vue
**Story:** [BI-1911](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1911)
A table column for environment year was added to the `Dataset.vue` component. The load method was changed to also fetch all studies and seasons for an experiment using the BrAPI proxy endpoints. A map of environment year using environment DbID as the key is then formed and used to populate the Env Year column when the dataset rows are formed.
A bug was fixed where the rep number was not displaying because the code was checking for "replicate" instead of the property "rep".
`ExperimentDAO#getDatasetById` was returning undefined and was fixed.
Various null checks, error checks,  and type assertions were added and general code clean up was done. 
bi-api-develop
1. Go to the …
=> [BI-1911] Environment Year Missing from Exp table

src/views/import/ImportExperiment.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1847
- Experiment & Observations template V05 renamed "Test (T) or Check (C )" to "Test (T) or Check (C)". (https://cornell.app.box.com/folder/154311239564)
- I changed the download link to the new template version hosted on Box.
https://github.com/Breeding-Insight/bi-api/pull/292
There's a TAF PR as well: https://github.com/Breeding-Insight/taf/pull/125
[See acceptance criteria on Jira](https://breedinginsight.atlassian.net/browse/BI-1847).
=> BI-1847 - Experiment import template formatting improvements

src/components/forms/DataForm.vue, src/components/tables/expandableTable/ExpandableTable.vue, src/views/germplasm/BreedingMethods.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1805
> Note: this is the second PR for BI-1805, it failed QA.
It was determined that the edit form fields and buttons should be hidden for in-use breeding methods. An informative message is shown in place of the edit form for in-use breeding methods.
- Create 2 new breeding methods in a program.
- Upload a germplasm file that uses one of those new breeding methods.
- Ensure that the unused breeding method can be edited and deleted.
- Ensure that the in-use breeding method cannot be edited or deleted, and an informational message is shown in place of the edit form.
=> BI-1805 - Conditionally Hide Edit Form and Buttons

src/views/import/ImportGermplasm.vue, src/views/import/ImportTemplate.vue
**Story:** [story in Jira](https://breedinginsight.atlassian.net/browse/BI-1799)
- Made the default page size 200.
- Removed the show all button.
I added a `initialPageSize` property to `ImportTemplate` with a default value to preserve the previous behavior while allowing consumers to pass their own default.
Upload a Germplasm file and ensure the preview table has a default page size of 200 and there is no show all button.
=> BI-1799 - Updated Germplasm Import Preview Pagination

src/views/experiments-and-observations/ExperimentDetails.vue
[BI-1926](https://breedinginsight.atlassian.net/browse/BI-1926) - Environment count incorrect
Comment out  the “Environments” count from the Experiment Details page.
view any experiments Details page.  The “Environments” count should not appear (it was below the "Germplasm" count in the summary section)
[BI-1926]: https://breedinginsight.atlassian.net/browse/BI-1926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1926 - Environment count incorrect

src/views/import/ImportExperiment.vue
[BI-1911](https://breedinginsight.atlassian.net/browse/BI-1911) - in response to Shahana's [testing notes.](https://breedinginsight.atlassian.net/browse/BI-1911?focusedCommentId=14057)
bi-api: bug/BI-1911-2 branch
- Import an Experiment.
- Look at the confirmation page.
**Expected Results**
- The `Env Year`, `Env`, and  `Exp unit ID` columns should appear as they did in the import file.
[BI-1911]: https://breedinginsight.atlassian.net/browse/BI-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1911 fix QA findings

src/breeding-insight/utils/GermplasmUtils.ts
**Story:** https://breedinginsight.atlassian.net/browse/BI-1927
- Fixed typo.
The bug occurred with old data that lacked the `listEntryNumbers` key in `additionalInfo`. The fix allows the frontend to fall-back on the `importEntryNumber`, as the import file represents the first/original list. (When support was added to DeltaBreed for multiple lists per Germplasm, the `listEntryNumbers` key was added). I've tested creating new lists with old germplasm data and it works; the first/original list position is stored by the `importEntryNumber`, while the subsequent lists will use `listEntryNumbers`.  When testing locally you can use BreedBase and
- upload Germplasm, with List name "NEW LIST",
- delete the list external reference from the database using the SQL below,
- go to the Germplasm List …
=> [BI-1927] - Entry Numbers Not Displaying

src/breeding-insight/utils/GermplasmUtils.ts
Identical code changes as https://github.com/Breeding-Insight/bi-web/pull/338, but based on `release/0.8.1`.
=> [BI-1927] - fixed typo

src/views/trait/TraitsImport.vue
**Story:** [BI-1935](https://breedinginsight.atlassian.net/browse/BI-1935?atlOrigin=eyJpIjoiNDgwNzZjZjMzZTgxNGQ5MGJlYzNhODgyNDc2YTE0MGQiLCJwIjoiaiJ9)
- Clear notifications like import template does
- None
- Verify that error notification is cleared when new file is uploaded after an existing error
[bi_ontology_template_v14_good.xlsx](https://github.com/Breeding-Insight/bi-web/files/13270919/bi_ontology_template_v14_good.xlsx)
[bi_ontology_template_v14_error.xlsx](https://github.com/Breeding-Insight/bi-web/files/13270920/bi_ontology_template_v14_error.xlsx)
[BI-1935]: https://breedinginsight.atlassian.net/browse/BI-1935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1935 - Error remains displayed

src/views/germplasm/GermplasmDetails.vue
**Story:** [BI-1958](https://breedinginsight.atlassian.net/browse/BI-1958?atlOrigin=eyJpIjoiOWE2Yjc4MzExNGRjNDY3MjkyNzlhOTI5ZmRlMjE5NjYiLCJwIjoiaiJ9)
- Removed images and attributes tabs from germplasm details view
- None
- Verify that images and attributes tabs are not visible in germplasm details view
[BI-1958]: https://breedinginsight.atlassian.net/browse/BI-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1958 - Hide images and attributes tabs from germplasm details

src/views/import/ImportFile.vue
**Story:** [BI-1963](https://breedinginsight.atlassian.net/browse/BI-1963?atlOrigin=eyJpIjoiZTMxY2NjODUyOWI3NDQwY2I4YmRiZWQzNDc1ZDFmYTUiLCJwIjoiaiJ9)
- Removed Data Mapping tab from import page
- None
- Verify Data Mapping tab is no longer shown on import page
[BI-1963]: https://breedinginsight.atlassian.net/browse/BI-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1963 - Remove Data Mapping tab from import page

src/views/import/Dataset.vue
[BI-1914](https://breedinginsight.atlassian.net/browse/BI-1914) - Improve exp dataset sort
Default sorting is now done on the back-end
bi-API:  feature/BI-1914 branch
- go to the Experiment detail page
- **the default order should be by `Env` and then `Exp Unit Id`**
[BI-1914]: https://breedinginsight.atlassian.net/browse/BI-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1914 - Improve exp dataset sort

src/breeding-insight/model/ActionMenuItem.ts, src/components/layouts/menus/ActionMenu.vue, src/views/germplasm/Germplasm.vue
[BI-1922](https://breedinginsight.atlassian.net/browse/BI-1922) Add ability to download all germplasm in a program
bi-api: feature/BI-1922
- From the side menu, select _Germplasm_ to see a list of all germplasm for the project
**Expected Result**
. the `Mange Germplasm` pull-down is visible. 
- Select `Download file` from the `Mange Germplasm` pull-down
**Expected Result**
. A file with the name `<project>_germplasm_<timestamp>.xlsx` should be downloaded.
. The file should contain all the correct information (except for `Female Parent Entry No` and `Male Parent Entry No`) for every germplasm in the project.
. The data should be in GID order.
[BI-1922]: https://breedinginsight.atlassian.net/browse/BI-1922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
=> BI-1922 (Add ability to download all germplasm in a program)

src/views/import/Dataset.vue
**Story:** [BI-1912](https://breedinginsight.atlassian.net/browse/BI-1912?atlOrigin=eyJpIjoiYjI2MDgwNjlmMGUyNDJiODkyZTM1ODdlZmQ1YzFlNjQiLCJwIjoiaiJ9)
- [Utilize more space before line wrapping text](https://github.com/Breeding-Insight/bi-web/pull/353/commits/999a51618bd48e24f2ea52593aea9a079ac10753)
- None
- Upload an experiment with long observation unit names and verify that the display text does not wrap as before.
[BI-1912]: https://breedinginsight.atlassian.net/browse/BI-1912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1912 - Wonky spacing on exp dataset summary

src/components/layouts/InfoSideBarLayout.vue
**Story:** [BI-2036](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2036)
The list of species-specific guest accounts in the sandbox sidebar is replaced with a single guest account.
none
Run bi-web in public sandbox mode and verify that only the single guest account is displayed.
[BI-2036]: https://breedinginsight.atlassian.net/browse/BI-2036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-2036] Update guest accounts listed in Sandbox left sidebar nav menu

src/views/import/ImportExperiment.vue
[BI-2029](https://breedinginsight.atlassian.net/browse/BI-2029) Experiment Preview and Visual Progress Indicators Broken in v0.9
In _ImportExperiment.vue_,the method _createObservationIndexMap()_ was setting values in _this.observationIndexMap_ that cause an out-of-bounds error in _cellClassIfExisting_.  This modifies _createObservationIndexMap()_ so that does not happen.
bi-api: development branch 
1) import an experiment with 2 or more observation variables.
Experiment preview is displayed.
[BI-2029]: https://breedinginsight.atlassian.net/browse/BI-2029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2029 (Experiment Preview and Visual Progress Indicators Broken in v0.90

package-lock.json, package.json, src/router/index.ts, src/views/BrAPI/BrAPIInfo.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-1921
_Please include a summary of the change that was made._
- bi-api/feature/BI-1921
- Latest version of FieldBook `main` branch
**Field Book QR Code BrAPI Config**
1. In DeltaBreed, navigate to a program
2. Navigate to the BrAPI menu
3. Ensure the "Field Book" tab is selected
4. In Field Book, navigate to the BrAPI settings screen
5. Tap the "Auto Configure" button, and choose to scan a configuration
6. Scan the QR code displayed on DeltaBreed
7. Ensure that the DeltaBreed config successfully imports into Field Book and that Field Book starts the process of authenticating against DeltaBreed
**Importing into Field Book**
_Pre-req: must already have set up the BrAPI connection to DeltaBreed_
1. In DeltaBreed, load an experiment …
=> BI-1921 - Support Field Book Study Import from DeltaBreed

src/views/import/ImportExperiment.vue, src/views/import/ImportTemplate.vue
**Story:** [BI-2008](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2008)
The template for the Vue component ImportExperiment was updated to match the wireframes in the card, including new summary fields for observation variables and observation level.
bi-api develop
Import an experiment and verify that the summary data for the preview matches the wireframe in the [parent card](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2003). Note: The value for the dataset field in the summary will not be correct for sub-obs units without the changes to the backend in [BI-1464](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1464). The preview table itself will not …
=> [BI-2008] Preview Summary Stats Refinement

src/views/import/ImportFile.vue
**Story:** [BI-2060](https://breedinginsight.atlassian.net/browse/BI-2060)
The value of env variable NODE_ENV is used to conditionally render the genotypic data tab so that it is gone in the production environment.
bi-api release/0.9
verify that the genotypic data tab is visible in development environment. Final verification to be done after deployment to production.
[BI-2060]: https://breedinginsight.atlassian.net/browse/BI-2060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-2060] Conditionally render the genotypic data import tab when running in production

src/views/BrAPI/BrAPIInfo.vue
**Story:** [BI-2059](https://breedinginsight.atlassian.net/browse/BI-2059?atlOrigin=eyJpIjoiZThkMWQ5NGJhMWJjNDE5OGI1YmRlODdhYTRhMWUxYmMiLCJwIjoiaiJ9)
- Changed default Field Book BrAPI category settings from Label to Value
- bi-api release/0.9
- Field Book 
- Scan QR code for BrAPI settings in Delta Breed and verify that the category option is set to Value in Field Book
- Verify that both nominal and ordinal traits have values displayed on buttons on collect screen in Field Book
[BI-2059]: https://breedinginsight.atlassian.net/browse/BI-2059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2059 - Field Book not displaying nominal categories from DeltaBreed

src/views/import/ImportGermplasm.vue
**COPIED FROM https://github.com/Breeding-Insight/bi-web/pull/370**
**Story:** [BI-1680](https://breedinginsight.atlassian.net/browse/BI-1680)
I updated the germplasm import template to remove the "Somoclone" breeding method from the Breeding Methods worksheet.
This [bi-api PR](https://github.com/Breeding-Insight/bi-api/pull/344) contains the corresponding database migration.
bi-api branch: `feature/BI-1680`.
1. Checkout this branch, `git checkout feature/BI-1680`.
2. Run DeltaBreed.
3. Download the germplasm import template.
- Ensure the template version is v10.
- Ensure the template Breeding Methods worksheet does not contain the "Somoclone" method.
[BI-1680]: https://breedinginsight.atlassian.net/browse/BI-1680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> BI-1680 - Updated Germplasm Template To Remove "Somoclone"

src/breeding-insight/model/Scale.ts, src/components/trait/forms/BaseTraitForm.vue, src/components/trait/forms/NumericalTraitForm.vue, tests/unit/components/tables/SidePanelTable.spec.ts
**Story:** https://breedinginsight.atlassian.net/browse/BI-2053
The NumericalTraitForm was sending the "units" input as "scaleName". I fixed this. It should have been done along with https://github.com/Breeding-Insight/bi-api/pull/331, but I missed this workflow.
Additionally, I renamed "unit" to "units" in a few places, to bring it in line with the BrAPI terminology.
Corresponding PR on bi-api: https://github.com/Breeding-Insight/bi-api/pull/342.
bi-api branch: `bug/BI-2053-fix`
In addition to the testing detailed on the [bi-api PR](https://github.com/Breeding-Insight/bi-api/pull/342), ensure that the form state is preserved as you change selection between Date, Ordinal, Nominal, Numerical and Text types.
=> BI-2053-fix - Fixed Trait Form Scale Units Handling

src/views/import/ImportTemplate.vue
[BI-2108](https://breedinginsight.atlassian.net/browse/BI-2108) Accessibility: Import Data - Empty Heading
Go to the _Import_ page
- There should be no empty header above the import template. (between the _tabs_ and the gray text box)
- Import pages should have consistent spacing above the import template. (between the _tabs_ and the gray text box)
[BI-2108]: https://breedinginsight.atlassian.net/browse/BI-2108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [feature/BI-2108] Accessibility: Import Data - Empty Heading

src/components/experiments/ExperimentsObservationsTable.vue, src/components/germplasm/GermplasmTable.vue, src/store/sorting/index.ts
**Story:** 
[BI-1969](https://breedinginsight.atlassian.net/browse/BI-1969) - Geologic sort: Germplasm, Experiments, and Sample Submission
- Go to the Germplasm page.
Germplasm are displayed in descending **GID** order.
- Go to the Experiments & Observations page
Experiment are displayed in descending **Create Date** order
[BI-1969]: https://breedinginsight.atlassian.net/browse/BI-1969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-1969] Geologic sort: Germplasm, Experiments, and Sample Submission

src/views/import/ImportGermplasm.vue
**Story:** [BI-1975](https://breedinginsight.atlassian.net/browse/BI-1975?atlOrigin=eyJpIjoiYTBhNTAxNTMzZWI2NDk0YmI0ZDM4Yjg1ODY5ODVmMTUiLCJwIjoiaiJ9)
- Updated link to germplasm import template
- bi-api bug/BI-1975
- Germplasm import accepts UNK and Unknown breeding methods for germplasm records
- Breeding methods in program administration page shows Increase for the UNK method class
[BI-1975]: https://breedinginsight.atlassian.net/browse/BI-1975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-1975 - "Unknown" Breeding Method not recognized

src/breeding-insight/model/GeoCoordinates.ts, src/breeding-insight/model/ObservationUnit.ts, src/views/import/Dataset.vue
**Story:** [BI-2167](https://breedinginsight.atlassian.net/browse/BI-2167?atlOrigin=eyJpIjoiN2NjMmZlNTk1ODdjNDVmZWFhNjQ0ZTFiMTc1YjQwYmIiLCJwIjoiaiJ9)
- Updated preview and experiment tables for correct [lon, lat, elevation] ordering
- Sent out message on delta breed channel noting implications for uploads prior to v0.10 release
- Shawn looked at production and there was no existing geocoordinate data that would need to be fixed
- bug/BI-2167 bi-api
Given I have an experiment import file with lat and long values
When I upload the file and subsequently download it from deltabreed
Then the Lat Long columns match the file that I uploaded instead of reversed
Given I have an experiment import file with lat and long values
When I upload the file 
Then I should see Lat and Long values matching …
=> BI-2167 - Lat and long values are getting swapped in the exp download file

src/components/layouts/VersionInfo.vue
[BI-2106](https://breedinginsight.atlassian.net/browse/BI-2106) Accessibility: Web Version
NOTE: To test this install the Siteimprove Accessibility Checker browser plugin found at https://chromewebstore.google.com/detail/siteimprove-accessibility/djcglbmbegflehmbfleechkjhmedcopn?pli=1
1. Go to any page with a side panel showing the web version
2. Run the Siteimprove Accessibility Checker
The Siteimprove Accessibility Checker should not report the issue `Text not included in an ARIA landmark`
[BI-2106]: https://breedinginsight.atlassian.net/browse/BI-2106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2106 -  Accessibility: Web Version

src/assets/scss/main.scss, src/views/Index.vue, src/views/NotAuthorized.vue
[BI-2103](https://breedinginsight.atlassian.net/browse/BI-2103) Accessibility: Links on Index and Not Authorized Pages
- On the index page, made the link to [www.breedinginsight.org](https://www.breedinginsight.org/) bold.
- On the Not Authorized page:
- - made the link to [contact your breeding program leader](http://localhost:8080/401#!) bold.
- - made the link to [DeltaBreed support](http://localhost:8080/401#!) bold.
NOTE: To test this install the Siteimprove Accessibility Checker browser plugin found at https://chromewebstore.google.com/detail/siteimprove-accessibility/djcglbmbegflehmbfleechkjhmedcopn?pli=1
1. Go to _Index_ page (go to Deltabreed without logging in)
The Siteimprove Accessibility Checker should **not** report the issue "Links are not …
=> [BI-2103] Accessibility: Links on Index and Not Authorized Pages

src/views/experiments-and-observations/ExperimentDetails.vue, src/views/import/Dataset.vue
[BI-2259](https://breedinginsight.atlassian.net/browse/BI-2259) - Disable Sub-entity Dataset option Mange experiments menu
Commented out the menu option for 'Create Sub-Entity Dataset'.  (it is assumed that it will be un-commented later)
(see also the Acceptance Criteria on [BI-2259](https://breedinginsight.atlassian.net/browse/BI-2259).)
1. Go to an Experiment
2. Click on the _Manage Experiment_ Menu.
**EXPECTED RESULT**
you should no longer see the _Create Sub-Entity Dataset_ optin
[BI-2259]: https://breedinginsight.atlassian.net/browse/BI-2259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BI-2259]: https://breedinginsight.atlassian.net/browse/BI-2259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> BI-2259 - Disable Sub-entity Dataset option Mange experiments menu

src/config/ability.ts, src/views/program/ProgramSelection.vue, tests/unit/components/program/ProgramUsersTable.spec.ts, tests/unit/components/tables/ExpandableTable.spec.ts, tests/unit/index.ts
**Story:** [BI-1692 - Change role names](https://breedinginsight.atlassian.net/browse/BI-1692)
Updated front end logic to use new role domains:
- admin -> System Administrator
- breeder -> Program Administrator
- member -> Read Only
Changed RolePermissions in ability.ts to utilize new domains
- This involved adding a helper method to remove whitespaces from domain names in order to convert domain names to rolePermissions function names 
bi-api: [feature/BI-1692](https://github.com/Breeding-Insight/bi-api/pull/377)
Ensure a user can can log in as:
- System Administrator
- Program Administrator
- Read Only
System User Table
- Check that System Administrator displays properly in role column
- Check that role dropdown for edit and creating a user now properly displays System Administrator and …
=> [BI-1692] - Change role names

src/components/forms/BasicInputField.vue, src/components/ontology/OntologyTable.vue, src/components/trait/TraitDetailPanel.vue, src/components/trait/forms/BaseTraitForm.vue
**Story:** [BI-2044](https://breedinginsight.atlassian.net/browse/BI-2044?atlOrigin=eyJpIjoiNzRiMmFhNGY0ZjMwNDUwM2I5N2RmNmE1N2I3ODhkMzkiLCJwIjoiaiJ9)
- Added isDisabled prop to src/components/forms/BasicInputField.vue
- Not used in this card was going to but decided on different approach, left in for possible future use
- Added editable and editableCheckLoading props to BaseTraitForm to facilitate hiding controls there
- Updated edit update logic to separate changing active status from updating trait, it was already using the /archive endpoint so just kept changes on the front end
**NOTE:** Seeing an issue testing this and on qa-test as well when switching between the Active and Archived tabs on the ontology page, the pages are blank and some api calls are not being made unless you do a …
=> BI-2044 - Can't archive an observation variable that is in use

src/views/import/ImportExperiment.vue
**Story:** [BI-2226](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2226)
Version 7 of the Experiment and Observations import template was created with the two columns referring to sub-observation units deleted. The UI link to download the template was updated to point to the new version.
none
Go to import Experiments and Observations and click on the button to download the import template. Verify that version 7 is downloaded and that it does not contain columns referencing sub observation units.
[BI-2226]: https://breedinginsight.atlassian.net/browse/BI-2226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2226 Experiment and Observations Template: Remove 2 sub-obs columns

package-lock.json, src/assets/scss/main.scss, src/breeding-insight/dao/ExperimentDAO.ts, src/breeding-insight/model/Collaborator.ts, src/breeding-insight/service/ExperimentService.ts, src/components/experiments/ExperimentAddCollaboratorModal.vue, src/components/experiments/ExperimentCollaboratorRemovalModal.vue, src/components/modals/AddCollaboratorModal.vue, src/components/modals/ConfirmationModal.vue, src/views/experiments-and-observations/ExperimentDetails.vue
**Story:** [BI-1693](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-1693)
This update introduces functionality to add and remove experimental collaborators in the ExperimentDetails.vue component. Two new modals, `<ExperimentAddCollaboratorModal>` and `<ExperimentCollaboratorRemovalModal>`, are implemented to handle collaborator management. The experiment action menu now includes an option to add collaborators. Additional methods and fields were added to manage collaborator states and retrieve data from the backend. In the UI, a list of assigned collaborators is displayed with options to revoke access. Supporting changes include new SCSS classes and backend service methods in `ExperimentService.ts` and `ExperimentDAO.ts` for managing …
=> BI-1693 Add Collaborator To And Remove From Experiment (UI)

src/components/layouts/UserSideBarLayout.vue, src/config/AppAbility.ts, src/config/ability.ts, src/views/experiments-and-observations/ExperimentDetails.vue
[BI-2152](https://breedinginsight.atlassian.net/browse/BI-2152) - Experimental Collaborator Front-end Permissions
**Hide all menu items except for home, experiments and observations, BrAPI**
1.  Added _subjects_ to `AppAbility.ts` to correspond to options in the side-bar menu.
2. In `ability.ts` add role permission list for _experimentalcollaborator_,  also mad the roll permission list explicit for _readonly_.
**Restrict Manage Experiments menu**
1. added `can('create', 'Collaborator');` to _programadministrator_ and _systemadministrator_ in `ability.ts`.
2. Modified the _ActionMenuItem_ in `ExperimentDetails.vue` to include `this.$ability.can('create',
'Collaborator')`.
bi-api: **develop** branch
1. Log in as an _Experimental Collaborator_ with at least on experiment assigned.
**Expected …
=> BI-2152 - Experimental Collaborator Front-end Permissions

src/assets/scss/main.scss, src/components/experiments/ExperimentAddCollaboratorModal.vue, src/config/ability.ts, src/views/experiments-and-observations/ExperimentDetails.vue
**Story:** [BI-2295 - Allow Experimental Collaborators To View Collaborators](https://breedinginsight.atlassian.net/browse/BI-2295)
UI Fixes to Enable Experimental Collaborator and Read Only users to see list of collaborators associated with an experiment
- Changed remove collaborator button to match other buttons in DeltaBreed
- Adjusted spacing for displayed collaborators on an experiment and placed collaborator email in parentheses
- Modified remove collaborator button to only display for roles with permissions to manage collaborators
- Adjusted ability.ts related logic to use "manage" rather than "create" collaborators to better clarify the permission
- Bolded link in Add Experimental Collaborator modal for accessibility purposes
bi-api: …
=> [BI-2295] - Allow Experimental Collaborators To View Collaborators

src/views/import/Dataset.vue
**Story:** [BI-2302 - Fix wonky colors](https://breedinginsight.atlassian.net/browse/BI-2302)
Small change to make text color of summary details for an experimental dataset properly contrasted against background
n/a
Navigate to experiment details page
Ensure that the summary details for a dataset are in dark rather than green font 
Ensure that contrast of summary details to background passes WAVE AA standard
=> [BI-2302] - Fix wonky colors

src/components/germplasm/GermplasmLink.vue
**Story:** [BI-2129 - Accessibility: Germplasm Table Fixes](https://breedinginsight.atlassian.net/browse/BI-2129)
Modified logic in GermplasmLink.vue to ensure that when there is only an empty string for germplasm GID no link is added (since an empty string is unfortunately truthy in vue if statements).
No changes were made for the second condition of the card as WAVE and SiteImprove are no longer detecting duplicate IDs on the Germplasm View Table.
n/a
Upload germplasm file that includes germplasm with both parents, germplasm with female parent only, germplasm with no parents, and germplasm
Tabbing test:
Navigate through the germplasm table by repeatedly clicking tab. Tab should only focus on links in the table with a valid GID and should skip over cells with no value.
Screen reader …
=> [BI-2129] - Accessibility: Germplasm Table Fixes

src/breeding-insight/utils/GermplasmUtils.ts
**Story:** https://breedinginsight.atlassian.net/browse/BI-2304
Since the `listEntryNumbers` additionalInfo key was removed in the back end change, I updated the front end to rely on `importEntryNumber` alone for display.
bi-api PR: https://github.com/Breeding-Insight/bi-api/pull/401
BrAPI-Java-TestServer PR: https://github.com/Breeding-Insight/brapi-Java-TestServer/pull/35
bi-api branch: [feature/BI-2304](https://github.com/Breeding-Insight/bi-api/tree/feature/BI-2304)
BrAPI-Java-TestServer branch: [feature/BI-2304](https://github.com/Breeding-Insight/brapi-Java-TestServer/tree/feature/BI-2304)
See testing section [in the bi-api PR](https://github.com/Breeding-Insight/bi-api/pull/401).
=> BI-2304 - Support Duplicate Germplasm in Lists Referencing Existing Germplasm

src/components/admin/AdminProgramsTable.vue, src/components/admin/AdminUsersTable.vue, src/components/experiments/ExperimentsObservationsTable.vue, src/components/germplasm/GermplasmListsTable.vue, src/components/germplasm/GermplasmTable.vue, src/components/ontology/OntologyTable.vue, src/components/program/ProgramLocationsTable.vue, src/components/program/ProgramUsersTable.vue, src/components/tables/expandableTable/ExpandableTable.vue, src/components/trait/TraitsImportTable.vue
**Story:** [BI-1933](https://breedinginsight.atlassian.net/browse/BI-1933)
A common pattern in bi-web is to have a get{Entities} method for the data in a table view that is called within the `mounted()` method of the component, while also having a `paginationChanged` method with a `@Watch` annotation reference an `PaginationController` that can also call get{Entities}. In some (but not all) cases, the `PaginationController` instance is mutated in the `mounted()` method. This resulted in the get{Entities} method being called twice on initial page load, and (maybe) because of the way Vue handles reactivity, the "empty" table message would sometimes flash on screen. The larger issue though was that the duplicate calls were unnecessary, and since `paginationChanged` already has …
=> BI-1933 - Erroneous message: No germplasm are currently defined for this program 

src/components/admin/AdminProgramsTable.vue, src/components/admin/AdminUsersTable.vue, src/components/experiments/ExperimentsObservationsTable.vue, src/components/germplasm/GermplasmListsTable.vue, src/components/germplasm/GermplasmTable.vue, src/components/ontology/OntologyTable.vue, src/components/program/ProgramLocationsTable.vue, src/components/program/ProgramUsersTable.vue, src/components/tables/expandableTable/ExpandableTable.vue, src/components/trait/TraitsImportTable.vue
See https://github.com/Breeding-Insight/bi-web/pull/404 for details.
=> BI-1933 - merging into release/1.0

src/assets/scss/main.scss
**Story:** [BI-2334](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2334)
The exp summary preview statistics text was darkened black.
none
Create or append an experiment and confirm that the blackish text in the green preview table box is pleasing to the eye.
[BI-2334]: https://breedinginsight.atlassian.net/browse/BI-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2334 Wonky Colors - Exp preview

src/views/program/JobManagement.vue
**Story:** [BI-2123](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2123)
The bugfix card described an issue where the right-most column on the Jobs table, containing the "Details" link, was inaccessible as it was running outside the available viewport for a laptop running the Brave browser. This behavior was not reproducible at the time that this story was worked on; however, it was noticed that the text in the "Status Message" column was getting cut off because the row height is not sufficient to display the full message. It was decided to remove the Status Message column to provide ample space for the Details column as a safeguard and to remove a redundant cut-off message that is available to read in full by clicking on the Details link. …
=> BI-2123 Jobs table sizing is wonky & hiding the "details" option

src/views/trait/TraitsImport.vue
[BI-2328](https://breedinginsight.atlassian.net/browse/BI-2328) Experimental observation file import removes periods from column headers
Change the link for the Ontology Import template to point to the new version (with "No periods are allowed" added to the `name` discription)
bi-api : **bug/BI-2328_fix**
insure that the ontology template button retrieves `bi_ontology_template_v15_2024-10-09`.
[BI-2328]: https://breedinginsight.atlassian.net/browse/BI-2328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-2328]  Experimental observation file import removes periods from column headers

src/views/trait/TraitsImport.vue
**Story:** [BI-2355 - Non-informative error message: regression](https://breedinginsight.atlassian.net/browse/BI-2355)
This error was due to tablesaw processing brackets weirdly, resulting in the column name stored in data not matching the column name stored in dynamic column names.
This part of the fix links to a new ontology import template that clarifies that brackets are invalid for ontology term name.
bi-api: [bug/BI-2355.2](https://github.com/Breeding-Insight/bi-api/pull/423)
Download ontology import template and ensure it mentions that brackets along with periods are invalid for ontology term name.
=>  [BI-2355] - Non-informative error message: regression

src/components/trait/forms/BaseTraitForm.vue
[BI-2364](https://breedinginsight.atlassian.net/browse/BI-2364) Downloaded ontology file had 'units' added to trait with scale class text.
Deleted lines in the setScaleClass(value: string) method, that set `units` to `value`. (`value` will be one of the following strings "Date", "Nominal", "Numerical", "Ordinal",or  "Text")
None.
WHEN user is on the Ontology List screen,
AND selects the 'Show details' link of an existing ontology,
AND select the 'Edit' link,
AND changes the `Scale` `Class` to anything besides "Numerical",
AND selects 'Save'.
WHEN user selects the 'Manage Ontology' pull-down,
AND selects 'Download File'.
THEN the row associated with the edited ontology should have a <blank> value in the `Units` column.
[BI-2364]: https://breedinginsight.atlassian.net/browse/BI-2364?atlOrigi …
=> BI-2364 Downloaded ontology file had 'units' added to trait with scale class text.

src/views/import/Dataset.vue
[BI-2342](https://breedinginsight.atlassian.net/browse/BI-2342) Experimental filtering is case specific
Made the custom search of observations (filterByObservations) case insensitive
see [Acceptance Criteria](https://breedinginsight.atlassian.net/browse/BI-2342) in story
[BI-2342]: https://breedinginsight.atlassian.net/browse/BI-2342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BI-2342] Experimental filtering is case specific

src/views/import/Dataset.vue, src/views/sample-mgmt/SubmissionDetails.vue
**Story:** [BI-2343 - GID filtering not informative](https://breedinginsight.atlassian.net/browse/BI-2343)
Changes to enable exact match GID filtering for multiple tables
For Experiment Details and Sample Submission Details tables, frontend search is used, so a custom-search function was added in the respective buefy files to do exact search filtering in the GID case.
For Germplasm and Germplasm list tables, backend search is used, which presently only does partial matching. Due to the high risk associated with modifying backend search to alternatively enable exact or partial match for each filter, ResponseUtils:search was slightly modified to do an exact match specifically when the filter is accessionNumber.
[bi-api: bug/BI-2343](https://github.com/Breeding-Insight/bi-api/pull/435)
On …
=> [BI-2343] - GID filtering not informative

package-lock.json, src/views/sample-mgmt/SubmissionDetails.vue
**Story:** [BI-2363](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/34?selectedIssue=BI-2363)
The plate details are fetched after manually updating the status to fix a bug where the data is cleared after updating.
none
Import some samples and go to view the sample details table in the Deltabreed UI. Select the "Mange Submission" button and choose "Manually Update Status". Change the status and save. Verify that the data is still visible for the "Plate Details" and "Submission Details" tabs.
[BI-2363]: https://breedinginsight.atlassian.net/browse/BI-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2363 Plate details & submission details disappear when status is manually updated

package-lock.json, src/assets/scss/main.scss, src/breeding-insight/dao/GermplasmDAO.ts, src/breeding-insight/model/ListFilter.ts, src/breeding-insight/service/GermplasmService.ts, src/breeding-insight/service/ListService.ts, src/components/germplasm/GermplasmListDeletionlModal.vue, src/components/germplasm/GermplasmTable.vue, src/config/AppAbility.ts, src/config/ability.ts, src/store/filtering/getters.ts, src/store/filtering/index.ts, src/store/filtering/mutations.ts, src/store/filtering/types.ts, src/util/ListType.ts, src/views/germplasm/GermplasmByList.vue, src/views/germplasm/GermplasmLists.vue
**Story:** [BI-2373](https://breedinginsight.atlassian.net/jira/software/c/projects/BI/boards/1?selectedIssue=BI-2373)
[BI-2372](https://github.com/Breeding-Insight/bi-api/pull/434) [BI-2374](https://github.com/Breeding-Insight/brapi-Java-TestServer/pull/38)
- Import a germplasm list to a project
- navigate to the project's germplasm lists table and click on the details link for the imported list
- in the list details table click on manage-list and select delete
- verify that the list no longer appears in the lists table
- navigate to the all-germplasm tab and verify that the individual germplasm contained in the deleted list are still present
- [] I have create/modified unit tests to cover this change
[BI-2373]: https://breedinginsight.atlassian.net/browse/BI-2373?atlOrigin=eyJpIjoiNWRkNT …
=> BI-2373 Add Delete Option to Germplasm Lists View

src/views/import/Dataset.vue
**Story:** [BI-2449 - Correct Exp Preview Summary Stats](https://breedinginsight.atlassian.net/browse/BI-2449)
Renaming and removing some of the experimental summary preview stats.
- Go to experiment details
- Ensure that the "Observation Unit", "Observations with Data", and  "Observations without Data" items are no longer present in the summary stats
- Ensure that the items "Observations" and "Observation Variables" are present and have the correct values
=> [BI-2449] - Correct Exp Preview Summary Stats

src/breeding-insight/dao/ExperimentDAO.ts, src/breeding-insight/service/ExperimentService.ts, src/components/experiments/ExperimentDeleteModal.vue
[BI-2496](https://breedinginsight.atlassian.net/browse/BI-2496) When Deleting an Experiment: "Success" message appears even if delete fails.
_Please include a summary of the change that was made._
Read the HTTP-status code returned from bi-api and use that to display the correct banner.
1.  Insure the "success" banner still appears when an experiment is successfully deleted.
2. An "error" banner should appear when the delete fails. (to insure the delete fails, I temporarily replace _ExperimentController::deleteExperiment_ with:
```
@Delete("/${micronaut.bi.api.version}/programs/{programId}/experiments/{experimentId}{?hard}")
@ProgramSecured(roles = {ProgramSecuredRole.PROGRAM_ADMIN, ProgramSecuredRole.SYSTEM_ADMIN})
@Produces(MediaType.APPLICATION_JSON)
public HttpResponse …
```
=> BI-2496 When Deleting an Experiment: "Success" message appears even if delete fails.

src/views/import/Dataset.vue, src/views/import/ImportExperiment.vue
**Story:** [BI-2449 - Correct Exp Preview Summary Stats](https://breedinginsight.atlassian.net/browse/BI-2449)
Renaming and removing some of the experimental summary preview stats.
The main change for this QA fix is clarifying that "Observations" actually means the count of observations recorded, not the observation variables x observation units (which is merely the ceiling for "observations")
- Go to experiment details
- Ensure that the "Observation Unit", "Observations with Data", and  "Observations without Data" items are no longer present in the summary stats
- Ensure that the items "Observations" and "Observation Variables" are present and have the correct values
- NOTE: Observations should equal the number of observations with values, NOT observation variables x …
=> [BI-2449-fix] - Correct Exp Preview Summary Stats, QA fix

src/views/experiments-and-observations/ExperimentDetails.vue
**Story:** [BI-2426](https://breedinginsight.atlassian.net/browse/BI-2426)
Sub-entity features will not be included in the v1.1 release.
This PR hides the sub-entity option in the dropdown menu.
[BI-2426]: https://breedinginsight.atlassian.net/browse/BI-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BI-2426 -  Disable Sub-Entity Features for v1.1 Release

src/components/layouts/NoSideBarLayout.vue
[BI-2140](https://breedinginsight.atlassian.net/browse/BI-2140) Accessibility: Home Page
**THE PROBLEM**
If a Program has not yet been selected then the property _title_ in NoSideBarLayout.vue will be blank, which will produce the HTML `<h1></h1>`.  This will cause the _Siteimprove_ errors:
```Empty headings →
A  1.3.1 Info and Relationships
AA 2.4.6 Headings and Labels
```
**THE SOLUTION**
In NoSideBarLayout.vue make the title HTML conditional. Changing:
`<h1 class="title has-text-primary level-item">{{title}}</h1>`
TO
`<h1 v-if="title" class="title has-text-primary level-item">{{title}}</h1>`
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._
- IF you have logged into DeltaBreed, 
- and IF you have not yest selected a program 
- and …
=> [BI-2140] Accessibility: Home Page

src/components/germplasm/GermplasmTable.vue, src/store/sorting/getters.ts, src/store/sorting/index.ts, src/store/sorting/mutation-types.ts, src/store/sorting/mutations.ts, src/store/sorting/types.ts, src/views/germplasm/AllGermplasm.vue, src/views/germplasm/GermplasmByList.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-2555
The `GermplasmTable` component is used by both `AllGermplasm` and `GermplasmByList`. Because `AllGermplasm` and `GermplasmByList` have different default sort requirements, and should both remember the user-selected sort when the user navigates away and back again, they needed to be updated to use different pieces of Vuex state. I moved the sorting state management up to the parent components, and added props for `germplasmSort` and `updateGermplasmSort` to `GermplasmTable`. 
None
- Upload germplasm to a program.
- Ensure the default sort of the all germplasm table is GID, descending.
- Ensure the default sort of the germplasm by list table is import entry number, ascending.
=> [BI-2555] - Fix Germplasm By List Default Sorting

src/components/trait/TraitImportTemplateMessageBox.vue, src/views/import/ImportExperiment.vue, src/views/import/ImportGermplasm.vue, src/views/import/ImportSample.vue, src/views/trait/TraitsImport.vue
**Story:** https://breedinginsight.atlassian.net/browse/BI-2574
Updated the download links for all template files to [the new Box folder](https://cornell.box.com/s/7ypfnp5disiz93lvgjnsm137lgbops3q).
> Note that `TraitImportTemplateMessageBox` was updated for completeness, it is not used anywhere.
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._
For each import template (germplasm, experiment, ontology and sample submission), ensure that
1. the download works,
2. the most recent template file is downloaded, and
3. the download link matches the share link in [the new Box folder](https://cornell.box.com/s/7ypfnp5disiz93lvgjnsm137lgbops3q).
=> [BI-2574] - Migrate documentation links to the new BOX
